/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */


use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use std::sync::Arc;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};
use crate::apis::ContentType;

#[cfg_attr(feature = "mockall", automock)]
#[async_trait]
pub trait AccountNumbersApi: Send + Sync {

    /// GET /v1/accounts/{accountId}/ach_numbers
    ///
    /// Retrieves full ACH routing and account numbers associated with a connected account.  These numbers can be sent to a payment processor to enable direct deposits and withdrawals from the account.  Please note that for the numbers be available, the account holder must have verified the account through a Connector enabled with the **Account Numbers** product. To be notified when the numbers are available, subscribe to the [`account.verified` webhook event](#tag/Event-Schemas/AccountEvent-Schema).  For Finicity accounts where ACH numbers have not been cached yet, a `202 Accepted` response will be returned while the numbers are fetched asynchronously. Retry the request. 
    async fn v1_accounts_account_id_ach_numbers_get<'account_id>(&self, account_id: &'account_id str) -> Result<models::AchNumbers, Error<V1AccountsAccountIdAchNumbersGetError>>;
}

pub struct AccountNumbersApiClient {
    configuration: Arc<configuration::Configuration>
}

impl AccountNumbersApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}



#[async_trait]
impl AccountNumbersApi for AccountNumbersApiClient {
    /// Retrieves full ACH routing and account numbers associated with a connected account.  These numbers can be sent to a payment processor to enable direct deposits and withdrawals from the account.  Please note that for the numbers be available, the account holder must have verified the account through a Connector enabled with the **Account Numbers** product. To be notified when the numbers are available, subscribe to the [`account.verified` webhook event](#tag/Event-Schemas/AccountEvent-Schema).  For Finicity accounts where ACH numbers have not been cached yet, a `202 Accepted` response will be returned while the numbers are fetched asynchronously. Retry the request. 
    async fn v1_accounts_account_id_ach_numbers_get<'account_id>(&self, account_id: &'account_id str) -> Result<models::AchNumbers, Error<V1AccountsAccountIdAchNumbersGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/v1/accounts/{accountId}/ach_numbers", local_var_configuration.base_path, accountId=crate::apis::urlencode(account_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_auth_conf) = local_var_configuration.basic_auth {
            local_var_req_builder = local_var_req_builder.basic_auth(local_var_auth_conf.0.to_owned(), local_var_auth_conf.1.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AchNumbers`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AchNumbers`")))),
            }
        } else {
            let local_var_entity: Option<V1AccountsAccountIdAchNumbersGetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

}

/// struct for typed errors of method [`AccountNumbersApi::v1_accounts_account_id_ach_numbers_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1AccountsAccountIdAchNumbersGetError {
    Status400(models::RestError),
    Status403(models::RestError),
    Status410(models::RestError),
    Status404(models::RestError),
    UnknownValue(serde_json::Value),
}

