/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */


use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use std::sync::Arc;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};
use crate::apis::ContentType;

#[cfg_attr(feature = "mockall", automock)]
#[async_trait]
pub trait ConnectionsApi: Send + Sync {

    /// POST /v1/connections/{connectionId}/transactions/refresh
    ///
    /// Triggers a Transactions Refresh for a given Connection.  Successful requests trigger a transaction sync from the Connection provider and return a `202 Accepted` response.  If transactions are added, removed, or updated, you will be notified via webhook events and the changes will be available in GraphQL. If there are no changes, no webhook will be fired — this mirrors the behavior of upstream providers, which only emit events when data changes.  **This feature is currently in beta.** Please contact [Quiltt Support](https://quiltt.io/support) to have it enabled for your environment. 
    async fn v1_connections_connection_id_transactions_refresh_post<'connection_id>(&self, connection_id: &'connection_id str) -> Result<(), Error<V1ConnectionsConnectionIdTransactionsRefreshPostError>>;

    /// GET /v1/profiles/{profileId}/connections/{connectionId}/export
    ///
    /// Exports the Connection details needed to make direct API calls to the underlying provider.  Contact Quiltt Support to enable this feature. 
    async fn v1_profiles_profile_id_connections_connection_id_export_get<'profile_id, 'connection_id>(&self, profile_id: &'profile_id str, connection_id: &'connection_id str) -> Result<models::ConnectionExport, Error<V1ProfilesProfileIdConnectionsConnectionIdExportGetError>>;

    /// POST /v1/profiles/{profileId}/connections/import/plaid
    ///
    /// Imports a Connection from an existing Plaid record. 
    async fn v1_profiles_profile_id_connections_import_plaid_post<'profile_id, 'connection_import_plaid_request>(&self, profile_id: &'profile_id str, connection_import_plaid_request: Option<models::ConnectionImportPlaidRequest>) -> Result<models::Connection, Error<V1ProfilesProfileIdConnectionsImportPlaidPostError>>;
}

pub struct ConnectionsApiClient {
    configuration: Arc<configuration::Configuration>
}

impl ConnectionsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}



#[async_trait]
impl ConnectionsApi for ConnectionsApiClient {
    /// Triggers a Transactions Refresh for a given Connection.  Successful requests trigger a transaction sync from the Connection provider and return a `202 Accepted` response.  If transactions are added, removed, or updated, you will be notified via webhook events and the changes will be available in GraphQL. If there are no changes, no webhook will be fired — this mirrors the behavior of upstream providers, which only emit events when data changes.  **This feature is currently in beta.** Please contact [Quiltt Support](https://quiltt.io/support) to have it enabled for your environment. 
    async fn v1_connections_connection_id_transactions_refresh_post<'connection_id>(&self, connection_id: &'connection_id str) -> Result<(), Error<V1ConnectionsConnectionIdTransactionsRefreshPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/v1/connections/{connectionId}/transactions/refresh", local_var_configuration.base_path, connectionId=crate::apis::urlencode(connection_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<V1ConnectionsConnectionIdTransactionsRefreshPostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Exports the Connection details needed to make direct API calls to the underlying provider.  Contact Quiltt Support to enable this feature. 
    async fn v1_profiles_profile_id_connections_connection_id_export_get<'profile_id, 'connection_id>(&self, profile_id: &'profile_id str, connection_id: &'connection_id str) -> Result<models::ConnectionExport, Error<V1ProfilesProfileIdConnectionsConnectionIdExportGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/v1/profiles/{profileId}/connections/{connectionId}/export", local_var_configuration.base_path, profileId=crate::apis::urlencode(profile_id), connectionId=crate::apis::urlencode(connection_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConnectionExport`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ConnectionExport`")))),
            }
        } else {
            let local_var_entity: Option<V1ProfilesProfileIdConnectionsConnectionIdExportGetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Imports a Connection from an existing Plaid record. 
    async fn v1_profiles_profile_id_connections_import_plaid_post<'profile_id, 'connection_import_plaid_request>(&self, profile_id: &'profile_id str, connection_import_plaid_request: Option<models::ConnectionImportPlaidRequest>) -> Result<models::Connection, Error<V1ProfilesProfileIdConnectionsImportPlaidPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/v1/profiles/{profileId}/connections/import/plaid", local_var_configuration.base_path, profileId=crate::apis::urlencode(profile_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&connection_import_plaid_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Connection`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Connection`")))),
            }
        } else {
            let local_var_entity: Option<V1ProfilesProfileIdConnectionsImportPlaidPostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

}

/// struct for typed errors of method [`ConnectionsApi::v1_connections_connection_id_transactions_refresh_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1ConnectionsConnectionIdTransactionsRefreshPostError {
    Status403(models::RestError),
    Status404(models::RestError),
    Status409(models::RestError),
    Status429(models::RestError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ConnectionsApi::v1_profiles_profile_id_connections_connection_id_export_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1ProfilesProfileIdConnectionsConnectionIdExportGetError {
    Status401(models::RestError),
    Status403(models::RestError),
    Status404(models::RestError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ConnectionsApi::v1_profiles_profile_id_connections_import_plaid_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1ProfilesProfileIdConnectionsImportPlaidPostError {
    Status400(models::RestError),
    Status403(models::RestError),
    Status404(models::RestError),
    Status409(models::RestError),
    Status422(std::collections::HashMap<String, Vec<String>>),
    Status429(models::RestError),
    UnknownValue(serde_json::Value),
}

