/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1AccountsAccountIdProcessorTokensPostRequest {
    /// The issuer of the Processor Token.  - `QUILTT` - Quiltt  - `MX` - MX  - `PLAID` - Plaid 
    #[serde(rename = "issuer", skip_serializing_if = "Option::is_none")]
    pub issuer: Option<Issuer>,
    /// The processor that will be receiving the Token.
    #[serde(rename = "processor", skip_serializing_if = "Option::is_none")]
    pub processor: Option<Processor>,
}

impl V1AccountsAccountIdProcessorTokensPostRequest {
    pub fn new() -> V1AccountsAccountIdProcessorTokensPostRequest {
        V1AccountsAccountIdProcessorTokensPostRequest {
            issuer: None,
            processor: None,
        }
    }
}
/// The issuer of the Processor Token.  - `QUILTT` - Quiltt  - `MX` - MX  - `PLAID` - Plaid 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Issuer {
    #[serde(rename = "QUILTT")]
    Quiltt,
    #[serde(rename = "MX")]
    Mx,
    #[serde(rename = "PLAID")]
    Plaid,
}

impl Default for Issuer {
    fn default() -> Issuer {
        Self::Quiltt
    }
}
/// The processor that will be receiving the Token.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Processor {
    #[serde(rename = "ACHQ")]
    Achq,
    #[serde(rename = "ADP_ROLL")]
    AdpRoll,
    #[serde(rename = "ADYEN")]
    Adyen,
    #[serde(rename = "ALLOY")]
    Alloy,
    #[serde(rename = "ALPACA")]
    Alpaca,
    #[serde(rename = "ANSA")]
    Ansa,
    #[serde(rename = "APEX_CLEARING")]
    ApexClearing,
    #[serde(rename = "ARRAY")]
    Array,
    #[serde(rename = "ASTRA")]
    Astra,
    #[serde(rename = "ATOMIC")]
    Atomic,
    #[serde(rename = "BAKKT")]
    Bakkt,
    #[serde(rename = "BLOOM_CREDIT")]
    BloomCredit,
    #[serde(rename = "BOND")]
    Bond,
    #[serde(rename = "BOOM")]
    Boom,
    #[serde(rename = "BRALE")]
    Brale,
    #[serde(rename = "CARDLESS")]
    Cardless,
    #[serde(rename = "CARDLYTICS")]
    Cardlytics,
    #[serde(rename = "CHECK")]
    Check,
    #[serde(rename = "CHECKBOOK")]
    Checkbook,
    #[serde(rename = "CHECKOUT")]
    Checkout,
    #[serde(rename = "CIRCLE")]
    Circle,
    #[serde(rename = "DRIVEWEALTH")]
    Drivewealth,
    #[serde(rename = "DWOLLA")]
    Dwolla,
    #[serde(rename = "ESUSU")]
    Esusu,
    #[serde(rename = "FIANT")]
    Fiant,
    #[serde(rename = "FINIX")]
    Finix,
    #[serde(rename = "FORTRESS_TRUST")]
    FortressTrust,
    #[serde(rename = "GAINBRIDGE")]
    Gainbridge,
    #[serde(rename = "GALILEO")]
    Galileo,
    #[serde(rename = "GEMINI")]
    Gemini,
    #[serde(rename = "GUSTO")]
    Gusto,
    #[serde(rename = "HIGHNOTE")]
    Highnote,
    #[serde(rename = "I2C")]
    I2C,
    #[serde(rename = "KNOT")]
    Knot,
    #[serde(rename = "LAYER")]
    Layer,
    #[serde(rename = "LITHIC")]
    Lithic,
    #[serde(rename = "LOANPRO")]
    Loanpro,
    #[serde(rename = "MARQETA")]
    Marqeta,
    #[serde(rename = "MOCK")]
    Mock,
    #[serde(rename = "MODERN_TREASURY")]
    ModernTreasury,
    #[serde(rename = "MOOV")]
    Moov,
    #[serde(rename = "NUVEI")]
    Nuvei,
    #[serde(rename = "OATFI")]
    Oatfi,
    #[serde(rename = "OCROLUS")]
    Ocrolus,
    #[serde(rename = "OPEN_LEDGER")]
    OpenLedger,
    #[serde(rename = "PARAFIN")]
    Parafin,
    #[serde(rename = "PAYNOTE")]
    Paynote,
    #[serde(rename = "PINWHEEL")]
    Pinwheel,
    #[serde(rename = "RISKIFIED")]
    Riskified,
    #[serde(rename = "RIZE")]
    Rize,
    #[serde(rename = "SARDINE")]
    Sardine,
    #[serde(rename = "SCRIBEUP")]
    Scribeup,
    #[serde(rename = "SFOX")]
    Sfox,
    #[serde(rename = "SILA")]
    Sila,
    #[serde(rename = "SILA_MONEY")]
    SilaMoney,
    #[serde(rename = "SOLID")]
    Solid,
    #[serde(rename = "STAKE")]
    Stake,
    #[serde(rename = "STRADDLE")]
    Straddle,
    #[serde(rename = "STRIPE")]
    Stripe,
    #[serde(rename = "SVB_API")]
    SvbApi,
    #[serde(rename = "TABA_PAY")]
    TabaPay,
    #[serde(rename = "TEAL")]
    Teal,
    #[serde(rename = "THREAD_BANK")]
    ThreadBank,
    #[serde(rename = "TREASURY_PRIME")]
    TreasuryPrime,
    #[serde(rename = "UNIT")]
    Unit,
    #[serde(rename = "UTB")]
    Utb,
    #[serde(rename = "VALON")]
    Valon,
    #[serde(rename = "VESTA")]
    Vesta,
    #[serde(rename = "VOPAY")]
    Vopay,
    #[serde(rename = "WEDBUSH")]
    Wedbush,
    #[serde(rename = "WEPAY")]
    Wepay,
    #[serde(rename = "WYRE")]
    Wyre,
    #[serde(rename = "ZERO_HASH")]
    ZeroHash,
    #[serde(rename = "ZUM_RAILS")]
    ZumRails,
}

impl Default for Processor {
    fn default() -> Processor {
        Self::Achq
    }
}

