/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountEvent : An Account Event represents a change pertaining to an Account for one of your Profiles  - `account.created` fires when a new Account is registered on a Profile. - `account.owners_verified` fires when an Account's owners have been identified and become   available in GraphQL. - `account.reconnected` fires when an existing Account has been associated with a new Connection.   This can occur when you reconnect to an Institution you had previously connected. - `account.verified` fires when an Account becomes verified for money movement and ACH Numbers   become available via the REST API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountEvent {
    /// The ID of the Event.
    #[serde(rename = "id")]
    pub id: String,
    /// The timestamp of when the Event occurred, in [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601).
    #[serde(rename = "at")]
    pub at: chrono::DateTime<chrono::FixedOffset>,
    /// The type of Account Event that occurred.
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "profile")]
    pub profile: Box<models::AccountEventProfile>,
    #[serde(rename = "record")]
    pub record: Box<models::AccountEventRecord>,
    /// Additional context associated with the Account Event. Currently the following Account events expose context via `metadata`:  - `account.reconnected`: will provide `from` and `to` containing objects for the old and new Connections respectively. The Connection objects will contain an `id` and `provider`.
    #[serde(rename = "metadata")]
    pub metadata: serde_json::Value,
}

impl AccountEvent {
    /// An Account Event represents a change pertaining to an Account for one of your Profiles  - `account.created` fires when a new Account is registered on a Profile. - `account.owners_verified` fires when an Account's owners have been identified and become   available in GraphQL. - `account.reconnected` fires when an existing Account has been associated with a new Connection.   This can occur when you reconnect to an Institution you had previously connected. - `account.verified` fires when an Account becomes verified for money movement and ACH Numbers   become available via the REST API.
    pub fn new(id: String, at: chrono::DateTime<chrono::FixedOffset>, r#type: Type, profile: models::AccountEventProfile, record: models::AccountEventRecord, metadata: serde_json::Value) -> AccountEvent {
        AccountEvent {
            id,
            at,
            r#type,
            profile: Box::new(profile),
            record: Box::new(record),
            metadata,
        }
    }
}
/// The type of Account Event that occurred.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "account.created")]
    AccountCreated,
    #[serde(rename = "account.owners_verified")]
    AccountOwnersVerified,
    #[serde(rename = "account.reconnected")]
    AccountReconnected,
    #[serde(rename = "account.verified")]
    AccountVerified,
}

impl Default for Type {
    fn default() -> Type {
        Self::AccountCreated
    }
}

