/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnInvestmentHolding {
    /// Percent breakdown by asset class.
    #[serde(rename = "assetClasses", skip_serializing_if = "Option::is_none")]
    pub asset_classes: Option<Vec<models::AnInvestmentHoldingAssetClassesInner>>,
    /// Cost is average of all purchases for holding.
    #[serde(rename = "averageCost", skip_serializing_if = "Option::is_none")]
    pub average_cost: Option<bool>,
    /// If true, indicates that this holding is used to maintain proceeds from sales, dividends, and other cash postings to the investment account.
    #[serde(rename = "cashAccount", skip_serializing_if = "Option::is_none")]
    pub cash_account: Option<bool>,
    /// Change in current price compared to previous day's close
    #[serde(rename = "changeInPrice", skip_serializing_if = "Option::is_none")]
    pub change_in_price: Option<f64>,
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Box<models::CurrencyEntity>>,
    #[serde(rename = "currentUnitPrice", skip_serializing_if = "Option::is_none")]
    pub current_unit_price: Option<f64>,
    /// Current unit price as of date
    #[serde(rename = "currentUnitPriceDate", skip_serializing_if = "Option::is_none")]
    pub current_unit_price_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "debtSecurity", skip_serializing_if = "Option::is_none")]
    pub debt_security: Option<Box<models::DebtSecurityEntity>>,
    /// Description of the holding
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// For CDs, bonds, and other time-based holdings.
    #[serde(rename = "expirationDate", skip_serializing_if = "Option::is_none")]
    pub expiration_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Required for bonds. Face value at the time of data retrieved.
    #[serde(rename = "faceValue", skip_serializing_if = "Option::is_none")]
    pub face_value: Option<f64>,
    /// Percent breakdown by FI-specific asset class percentage breakdown
    #[serde(rename = "fiAssetClasses", skip_serializing_if = "Option::is_none")]
    pub fi_asset_classes: Option<Vec<models::AnInvestmentHoldingFiAssetClassesInner>>,
    #[serde(rename = "fiAttributes", skip_serializing_if = "Option::is_none")]
    pub fi_attributes: Option<Vec<models::FiAttributeEntity>>,
    /// Sub-account
    #[serde(rename = "heldInAccount", skip_serializing_if = "Option::is_none")]
    pub held_in_account: Option<HeldInAccount>,
    /// Long term persistent identity of the holding
    #[serde(rename = "holdingId", skip_serializing_if = "Option::is_none")]
    pub holding_id: Option<String>,
    /// Holding name or security name
    #[serde(rename = "holdingName", skip_serializing_if = "Option::is_none")]
    pub holding_name: Option<String>,
    #[serde(rename = "holdingSubType", skip_serializing_if = "Option::is_none")]
    pub holding_sub_type: Option<HoldingSubType>,
    #[serde(rename = "holdingType", skip_serializing_if = "Option::is_none")]
    pub holding_type: Option<HoldingType>,
    /// Source for money for this security. 
    #[serde(rename = "inv401kSurce", skip_serializing_if = "Option::is_none")]
    pub inv401k_surce: Option<Inv401kSurce>,
    /// Market value at the time of data retrieved
    #[serde(rename = "marketValue", skip_serializing_if = "Option::is_none")]
    pub market_value: Option<f64>,
    #[serde(rename = "mutualFundSecurity", skip_serializing_if = "Option::is_none")]
    pub mutual_fund_security: Option<Box<models::MutualFundSecurityEntity>>,
    #[serde(rename = "optionSecurity", skip_serializing_if = "Option::is_none")]
    pub option_security: Option<Box<models::OptionSecurityEntity>>,
    /// Date of original purchase
    #[serde(rename = "originalPurchaseDate", skip_serializing_if = "Option::is_none")]
    pub original_purchase_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "otherSecurity", skip_serializing_if = "Option::is_none")]
    pub other_security: Option<Box<models::OtherSecurityEntity>>,
    #[serde(rename = "positionType", skip_serializing_if = "Option::is_none")]
    pub position_type: Option<PositionType>,
    /// Price of holding at the time of purchase
    #[serde(rename = "purchasedPrice", skip_serializing_if = "Option::is_none")]
    pub purchased_price: Option<f64>,
    /// For CDs, bonds, and other rate based holdings.
    #[serde(rename = "rate", skip_serializing_if = "Option::is_none")]
    pub rate: Option<f64>,
    /// Unique identifier of security
    #[serde(rename = "securityId", skip_serializing_if = "Option::is_none")]
    pub security_id: Option<String>,
    /// Security identifier type
    #[serde(rename = "securityIdType", skip_serializing_if = "Option::is_none")]
    pub security_id_type: Option<SecurityIdType>,
    #[serde(rename = "stockSecurity", skip_serializing_if = "Option::is_none")]
    pub stock_security: Option<Box<models::StockSecurityEntity>>,
    #[serde(rename = "sweepSecurity", skip_serializing_if = "Option::is_none")]
    pub sweep_security: Option<Box<models::SweepSecurityEntity>>,
    /// Ticker / Market symbol
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Breakdown by tax lot.
    #[serde(rename = "taxLots", skip_serializing_if = "Option::is_none")]
    pub tax_lots: Option<Vec<models::AnInvestmentHoldingTaxLotsInner>>,
    /// Required for stock, mutual funds. Number of shares (with decimals).
    #[serde(rename = "units", skip_serializing_if = "Option::is_none")]
    pub units: Option<f64>,
}

impl AnInvestmentHolding {
    pub fn new() -> AnInvestmentHolding {
        AnInvestmentHolding {
            asset_classes: None,
            average_cost: None,
            cash_account: None,
            change_in_price: None,
            currency: None,
            current_unit_price: None,
            current_unit_price_date: None,
            debt_security: None,
            description: None,
            expiration_date: None,
            face_value: None,
            fi_asset_classes: None,
            fi_attributes: None,
            held_in_account: None,
            holding_id: None,
            holding_name: None,
            holding_sub_type: None,
            holding_type: None,
            inv401k_surce: None,
            market_value: None,
            mutual_fund_security: None,
            option_security: None,
            original_purchase_date: None,
            other_security: None,
            position_type: None,
            purchased_price: None,
            rate: None,
            security_id: None,
            security_id_type: None,
            stock_security: None,
            sweep_security: None,
            symbol: None,
            tax_lots: None,
            units: None,
        }
    }
}
/// Sub-account
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HeldInAccount {
    #[serde(rename = "CASH")]
    Cash,
    #[serde(rename = "MARGIN")]
    Margin,
    #[serde(rename = "SHORT")]
    Short,
    #[serde(rename = "OTHER")]
    Other,
}

impl Default for HeldInAccount {
    fn default() -> HeldInAccount {
        Self::Cash
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HoldingSubType {
    #[serde(rename = "MONEYMARKET")]
    Moneymarket,
    #[serde(rename = "CASH")]
    Cash,
}

impl Default for HoldingSubType {
    fn default() -> HoldingSubType {
        Self::Moneymarket
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HoldingType {
    #[serde(rename = "STOCK")]
    Stock,
    #[serde(rename = "BOND")]
    Bond,
    #[serde(rename = "MUTUALFUND")]
    Mutualfund,
    #[serde(rename = "CD")]
    Cd,
    #[serde(rename = "ANNUITY")]
    Annuity,
    #[serde(rename = "OPTION")]
    Option,
    #[serde(rename = "OTHER")]
    Other,
}

impl Default for HoldingType {
    fn default() -> HoldingType {
        Self::Stock
    }
}
/// Source for money for this security. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Inv401kSurce {
    #[serde(rename = "PRETAX")]
    Pretax,
    #[serde(rename = "AFTERTAX")]
    Aftertax,
    #[serde(rename = "MATCH")]
    Match,
    #[serde(rename = "PROFITSHARING")]
    Profitsharing,
    #[serde(rename = "ROLLOVER")]
    Rollover,
    #[serde(rename = "OTHERVEST")]
    Othervest,
    #[serde(rename = "OTHERNONVEST")]
    Othernonvest,
}

impl Default for Inv401kSurce {
    fn default() -> Inv401kSurce {
        Self::Pretax
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PositionType {
    #[serde(rename = "LONG")]
    Long,
    #[serde(rename = "SHORT")]
    Short,
}

impl Default for PositionType {
    fn default() -> PositionType {
        Self::Long
    }
}
/// Security identifier type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityIdType {
    #[serde(rename = "CUSIP")]
    Cusip,
    #[serde(rename = "ISIN")]
    Isin,
    #[serde(rename = "SEDOL")]
    Sedol,
    #[serde(rename = "SICC")]
    Sicc,
    #[serde(rename = "VALOR")]
    Valor,
    #[serde(rename = "WKN")]
    Wkn,
}

impl Default for SecurityIdType {
    fn default() -> SecurityIdType {
        Self::Cusip
    }
}

