/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BalanceEvent : A Balance Event represents a change pertaining to a Balance in your Quiltt Environment.  - `balance.created` fires when a new Balance is created in your Environment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BalanceEvent {
    /// The ID of the Event.
    #[serde(rename = "id")]
    pub id: String,
    /// The timestamp of when the Event occurred, in [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601).
    #[serde(rename = "at")]
    pub at: chrono::DateTime<chrono::FixedOffset>,
    /// The type of Balance Event that occurred.
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "profile")]
    pub profile: Box<models::AccountEventProfile>,
    #[serde(rename = "record")]
    pub record: Box<models::BalanceEventRecord>,
    /// Currently there is no metadata available for Balance events.
    #[serde(rename = "metadata")]
    pub metadata: serde_json::Value,
}

impl BalanceEvent {
    /// A Balance Event represents a change pertaining to a Balance in your Quiltt Environment.  - `balance.created` fires when a new Balance is created in your Environment.
    pub fn new(id: String, at: chrono::DateTime<chrono::FixedOffset>, r#type: Type, profile: models::AccountEventProfile, record: models::BalanceEventRecord, metadata: serde_json::Value) -> BalanceEvent {
        BalanceEvent {
            id,
            at,
            r#type,
            profile: Box::new(profile),
            record: Box::new(record),
            metadata,
        }
    }
}
/// The type of Balance Event that occurred.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "balance.created")]
    BalanceCreated,
}

impl Default for Type {
    fn default() -> Type {
        Self::BalanceCreated
    }
}

