/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BalanceEventRecord {
    /// The ID of the Balance.
    #[serde(rename = "id")]
    pub id: String,
    /// The ID of the Account.
    #[serde(rename = "accountId")]
    pub account_id: String,
    /// The timestamp of the Account Balance record.
    #[serde(rename = "at")]
    pub at: chrono::DateTime<chrono::FixedOffset>,
    /// The source of the Balance data.  Note that this enum is extensible and new values may be added over time.  - `INITIAL` - Initial value from the provider.  - `SYNC` - Regular sync with the provider.  - `REFRESH` - Provider response from a triggered **Refresh Balance** call. 
    #[serde(rename = "source")]
    pub source: Source,
    /// The amount of funds accounting for pending Transactions. For asset accounts (checking, savings, investment), a positive balance indicates money in the account and a negative balance indicates the account holder owing the institution. For liability accounts (credit cards, loans), a negative balance indicates the amount owed and a positive amount indicates the lender owing the account holder.
    #[serde(rename = "available", deserialize_with = "Option::deserialize")]
    pub available: Option<f64>,
    /// The amount of funds based on posted Transactions. For asset accounts (checking, savings, investment), a positive balance indicates money in the account and a negative balance indicates the account holder owing the institution. For liability accounts (credit cards, loans), a negative balance indicates the amount owed and a positive amount indicates the lender owing the account holder.
    #[serde(rename = "current", deserialize_with = "Option::deserialize")]
    pub current: Option<f64>,
    /// The amount of funds that may be overdraft or spent on credit.
    #[serde(rename = "limit", deserialize_with = "Option::deserialize")]
    pub limit: Option<f64>,
}

impl BalanceEventRecord {
    pub fn new(id: String, account_id: String, at: chrono::DateTime<chrono::FixedOffset>, source: Source, available: Option<f64>, current: Option<f64>, limit: Option<f64>) -> BalanceEventRecord {
        BalanceEventRecord {
            id,
            account_id,
            at,
            source,
            available,
            current,
            limit,
        }
    }
}
/// The source of the Balance data.  Note that this enum is extensible and new values may be added over time.  - `INITIAL` - Initial value from the provider.  - `SYNC` - Regular sync with the provider.  - `REFRESH` - Provider response from a triggered **Refresh Balance** call. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Source {
    #[serde(rename = "INITIAL")]
    Initial,
    #[serde(rename = "SYNC")]
    Sync,
    #[serde(rename = "REFRESH")]
    Refresh,
}

impl Default for Source {
    fn default() -> Source {
        Self::Initial
    }
}

