/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConnectionEvent : A Connection Event represents a change pertaining to a Connection on one of your Profiles.  - `connection.created` fires once a new Connection is created on a Profile. Note that it is highly recommended that you use the Connector `onExitSuccess` callback to track new Connections being created.  - `connection.synced.successful` fires when a Connection is successfully synced with the provider.  - `connection.synced.successful.initial` fires once after the first quick sync is completed on a Connection.  - `connection.synced.successful.historical` fires after historical data is synced following a successful Connector session. This includes both initial connections and Reconnect flows.  - `connection.synced.errored.repairable` fires when a Connection becomes `ERROR_REPAIRABLE` and requires  user action to resume syncing. Have the user complete the Connector [Reconnect flow](https://quiltt.dev/connector/reconnect) to resolve this error.  - `connection.synced.errored.institution` fires when the provider is reporting an error with the connected Institution.  - `connection.synced.errored.provider` fires when the Connection provider is reporting an error with the Connection. Inspect the Connection's [Remote Data](https://quiltt.dev/api/remote-data) for more information.  - `connection.synced.errored.service` fires when an unexpected error occurs attempting to sync the Connection. Visit our [Status page](https://status.quiltt.io) or contact Quiltt Support for more information.  - `connection.disconnected` fires when a Connection has been been fully disconnected from the provider.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionEvent {
    /// The ID of the Event.
    #[serde(rename = "id")]
    pub id: String,
    /// The timestamp of when the Event occurred, in [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601).
    #[serde(rename = "at")]
    pub at: chrono::DateTime<chrono::FixedOffset>,
    /// The type of Connection Event that occurred.
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "profile")]
    pub profile: Box<models::AccountEventProfile>,
    #[serde(rename = "record")]
    pub record: Box<models::ConnectionEventRecord>,
    /// Additional context associated with the Connection Event. Currently the following Connection events expose context via `metadata`:  - `connection.synced.successful*`: may provide an optional `startDate`/`endDate` pair indicating the date range of new data synced for the Connection.
    #[serde(rename = "metadata")]
    pub metadata: serde_json::Value,
}

impl ConnectionEvent {
    /// A Connection Event represents a change pertaining to a Connection on one of your Profiles.  - `connection.created` fires once a new Connection is created on a Profile. Note that it is highly recommended that you use the Connector `onExitSuccess` callback to track new Connections being created.  - `connection.synced.successful` fires when a Connection is successfully synced with the provider.  - `connection.synced.successful.initial` fires once after the first quick sync is completed on a Connection.  - `connection.synced.successful.historical` fires after historical data is synced following a successful Connector session. This includes both initial connections and Reconnect flows.  - `connection.synced.errored.repairable` fires when a Connection becomes `ERROR_REPAIRABLE` and requires  user action to resume syncing. Have the user complete the Connector [Reconnect flow](https://quiltt.dev/connector/reconnect) to resolve this error.  - `connection.synced.errored.institution` fires when the provider is reporting an error with the connected Institution.  - `connection.synced.errored.provider` fires when the Connection provider is reporting an error with the Connection. Inspect the Connection's [Remote Data](https://quiltt.dev/api/remote-data) for more information.  - `connection.synced.errored.service` fires when an unexpected error occurs attempting to sync the Connection. Visit our [Status page](https://status.quiltt.io) or contact Quiltt Support for more information.  - `connection.disconnected` fires when a Connection has been been fully disconnected from the provider.
    pub fn new(id: String, at: chrono::DateTime<chrono::FixedOffset>, r#type: Type, profile: models::AccountEventProfile, record: models::ConnectionEventRecord, metadata: serde_json::Value) -> ConnectionEvent {
        ConnectionEvent {
            id,
            at,
            r#type,
            profile: Box::new(profile),
            record: Box::new(record),
            metadata,
        }
    }
}
/// The type of Connection Event that occurred.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "connection.created")]
    ConnectionCreated,
    #[serde(rename = "connection.synced.successful")]
    ConnectionSyncedSuccessful,
    #[serde(rename = "connection.synced.successful.initial")]
    ConnectionSyncedSuccessfulInitial,
    #[serde(rename = "connection.synced.successful.historical")]
    ConnectionSyncedSuccessfulHistorical,
    #[serde(rename = "connection.synced.errored.repairable")]
    ConnectionSyncedErroredRepairable,
    #[serde(rename = "connection.synced.errored.institution")]
    ConnectionSyncedErroredInstitution,
    #[serde(rename = "connection.synced.errored.provider")]
    ConnectionSyncedErroredProvider,
    #[serde(rename = "connection.synced.errored.service")]
    ConnectionSyncedErroredService,
    #[serde(rename = "connection.disconnected")]
    ConnectionDisconnected,
}

impl Default for Type {
    fn default() -> Type {
        Self::ConnectionCreated
    }
}

