/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Connection : A Connection represents the data source for a Profile's accounts and transactions, such as a Finicity **Institution Login**, MX **Member** or Plaid **Item**.  The easiest way to register connections is with the Quiltt Connector, which handles the configuration for Finicity Connect, MX Connect and Plaid Link.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Connection {
    /// The ID of the Connection.
    #[serde(rename = "id")]
    pub id: String,
    /// The UTC date and time of the most recently known state of the Connection.  For active Connections, this is when data was last successfully synced with the upstream provider. For disconnected Connections, this is the time of the disconnection from the upstream provider.
    #[serde(rename = "at")]
    pub at: chrono::DateTime<chrono::FixedOffset>,
    /// Represents the data provider for the Connection.  - `AKOYA` - Akoya  - `FINICITY` - Finicity  - `MOCK` - Mock data  - `MX` - MX  - `PLAID` - Plaid  - `DISCONNECTED` - Disconnected 
    #[serde(rename = "provider")]
    pub provider: Provider,
    /// The products currently enabled on the Connection.
    #[serde(rename = "features")]
    pub features: Vec<Features>,
    /// The products currently enabled on the Connection.
    #[serde(rename = "products")]
    pub products: Vec<Products>,
    /// Represents the current state of a Connection.  See the [Connection docs](https://quiltt.dev/api/connections) for help troubleshooting error statuses.  Note that this enum is extensible and new values may be added over time.  - `INITIALIZING` - The Connection is being initialized and will begin syncing soon.  - `SYNCING` - The Connection is currently syncing with the provider.  - `SYNCED` - The Connection is synced and up to date with the provider.  - `ERROR_REPAIRABLE` - The Connection must be re-authenticated to resume syncing. Quiltt will keep trying to sync this Connection until it is re-authenticated.  - `ERROR_SERVICE` - Quiltt is experiencing an internal error attempting to sync this Connection. The Quiltt team has been notified and the Connection will be retried automatically once the issue is resolved.  - `ERROR_PROVIDER` - The Connection provider is reporting an error with the Connection. Quiltt will keep trying to sync this Connection until the error is resolved.  - `ERROR_INSTITUTION` - The Connection provider is reporting an error from the user's Institution. Quiltt will keep trying to sync this Connection until the error is resolved.  - `DISCONNECTING` - The Connection is in the process of being disconnected from its provider.  - `DISCONNECTED` - The Connection has been fully disconnected from the provider.  Accounts and associated data will remain on the Profile, but no new data will be synced until another Connection is established to the same Institution.  You can leverage the Connector [Reconnect flow](https://quiltt.dev/connector/reconnect) to prompt the user to re-establish the Connection. 
    #[serde(rename = "status")]
    pub status: Status,
    /// Custom metadata about the Connection, stored in a 'key-value' format.  See the [Custom Metadata](https://quiltt.dev/api/custom-metadata) guide for more information and examples.
    #[serde(rename = "metadata", deserialize_with = "Option::deserialize")]
    pub metadata: Option<serde_json::Value>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl Connection {
    /// A Connection represents the data source for a Profile's accounts and transactions, such as a Finicity **Institution Login**, MX **Member** or Plaid **Item**.  The easiest way to register connections is with the Quiltt Connector, which handles the configuration for Finicity Connect, MX Connect and Plaid Link.
    pub fn new(id: String, at: chrono::DateTime<chrono::FixedOffset>, provider: Provider, features: Vec<Features>, products: Vec<Products>, status: Status, metadata: Option<serde_json::Value>, created_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>) -> Connection {
        Connection {
            id,
            at,
            provider,
            features,
            products,
            status,
            metadata,
            created_at,
            updated_at,
        }
    }
}
/// Represents the data provider for the Connection.  - `AKOYA` - Akoya  - `FINICITY` - Finicity  - `MOCK` - Mock data  - `MX` - MX  - `PLAID` - Plaid  - `DISCONNECTED` - Disconnected 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "AKOYA")]
    Akoya,
    #[serde(rename = "FINICITY")]
    Finicity,
    #[serde(rename = "MOCK")]
    Mock,
    #[serde(rename = "MX")]
    Mx,
    #[serde(rename = "PLAID")]
    Plaid,
    #[serde(rename = "DISCONNECTED")]
    Disconnected,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::Akoya
    }
}
/// The products currently enabled on the Connection.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Features {
    #[serde(rename = "ACCOUNT_BALANCES_AND_TRANSACTIONS")]
    AccountBalancesAndTransactions,
    #[serde(rename = "ACCOUNT_NUMBERS")]
    AccountNumbers,
    #[serde(rename = "ACCOUNT_OWNERS")]
    AccountOwners,
    #[serde(rename = "ACCOUNT_STATEMENTS")]
    AccountStatements,
    #[serde(rename = "INVESTMENTS")]
    Investments,
    #[serde(rename = "LIABILITIES")]
    Liabilities,
    #[serde(rename = "ACCOUNT_BALANCE_REFRESHES")]
    AccountBalanceRefreshes,
    #[serde(rename = "ACCOUNT_TRANSACTIONS_REFRESHES")]
    AccountTransactionsRefreshes,
}

impl Default for Features {
    fn default() -> Features {
        Self::AccountBalancesAndTransactions
    }
}
/// The products currently enabled on the Connection.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Products {
    #[serde(rename = "ACCOUNT_BALANCES_AND_TRANSACTIONS")]
    AccountBalancesAndTransactions,
    #[serde(rename = "ACCOUNT_NUMBERS")]
    AccountNumbers,
    #[serde(rename = "ACCOUNT_OWNERS")]
    AccountOwners,
    #[serde(rename = "ACCOUNT_STATEMENTS")]
    AccountStatements,
    #[serde(rename = "INVESTMENTS")]
    Investments,
    #[serde(rename = "LIABILITIES")]
    Liabilities,
    #[serde(rename = "ACCOUNT_BALANCE_REFRESHES")]
    AccountBalanceRefreshes,
    #[serde(rename = "ACCOUNT_TRANSACTIONS_REFRESHES")]
    AccountTransactionsRefreshes,
}

impl Default for Products {
    fn default() -> Products {
        Self::AccountBalancesAndTransactions
    }
}
/// Represents the current state of a Connection.  See the [Connection docs](https://quiltt.dev/api/connections) for help troubleshooting error statuses.  Note that this enum is extensible and new values may be added over time.  - `INITIALIZING` - The Connection is being initialized and will begin syncing soon.  - `SYNCING` - The Connection is currently syncing with the provider.  - `SYNCED` - The Connection is synced and up to date with the provider.  - `ERROR_REPAIRABLE` - The Connection must be re-authenticated to resume syncing. Quiltt will keep trying to sync this Connection until it is re-authenticated.  - `ERROR_SERVICE` - Quiltt is experiencing an internal error attempting to sync this Connection. The Quiltt team has been notified and the Connection will be retried automatically once the issue is resolved.  - `ERROR_PROVIDER` - The Connection provider is reporting an error with the Connection. Quiltt will keep trying to sync this Connection until the error is resolved.  - `ERROR_INSTITUTION` - The Connection provider is reporting an error from the user's Institution. Quiltt will keep trying to sync this Connection until the error is resolved.  - `DISCONNECTING` - The Connection is in the process of being disconnected from its provider.  - `DISCONNECTED` - The Connection has been fully disconnected from the provider.  Accounts and associated data will remain on the Profile, but no new data will be synced until another Connection is established to the same Institution.  You can leverage the Connector [Reconnect flow](https://quiltt.dev/connector/reconnect) to prompt the user to re-establish the Connection. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "INITIALIZING")]
    Initializing,
    #[serde(rename = "SYNCING")]
    Syncing,
    #[serde(rename = "SYNCED")]
    Synced,
    #[serde(rename = "ERROR_REPAIRABLE")]
    ErrorRepairable,
    #[serde(rename = "ERROR_SERVICE")]
    ErrorService,
    #[serde(rename = "ERROR_PROVIDER")]
    ErrorProvider,
    #[serde(rename = "ERROR_INSTITUTION")]
    ErrorInstitution,
    #[serde(rename = "DISCONNECTING")]
    Disconnecting,
    #[serde(rename = "DISCONNECTED")]
    Disconnected,
}

impl Default for Status {
    fn default() -> Status {
        Self::Initializing
    }
}

