/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConnectionExport : Connection details needed to make direct requests to the provider's API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionExport {
    /// The ID of the Connection.
    #[serde(rename = "id")]
    pub id: String,
    /// The ID of the Profile.
    #[serde(rename = "profileId")]
    pub profile_id: String,
    /// Represents the data provider for the Connection.  - `AKOYA` - Akoya  - `FINICITY` - Finicity  - `MOCK` - Mock data  - `MX` - MX  - `PLAID` - Plaid 
    #[serde(rename = "provider")]
    pub provider: Provider,
    /// The provider's API key for the Connection.
    #[serde(rename = "apiKey")]
    pub api_key: Vec<String>,
}

impl ConnectionExport {
    /// Connection details needed to make direct requests to the provider's API.
    pub fn new(id: String, profile_id: String, provider: Provider, api_key: Vec<String>) -> ConnectionExport {
        ConnectionExport {
            id,
            profile_id,
            provider,
            api_key,
        }
    }
}
/// Represents the data provider for the Connection.  - `AKOYA` - Akoya  - `FINICITY` - Finicity  - `MOCK` - Mock data  - `MX` - MX  - `PLAID` - Plaid 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "AKOYA")]
    Akoya,
    #[serde(rename = "FINICITY")]
    Finicity,
    #[serde(rename = "MOCK")]
    Mock,
    #[serde(rename = "MX")]
    Mx,
    #[serde(rename = "PLAID")]
    Plaid,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::Akoya
    }
}

