/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreditCardLiability : An object representing a credit card account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditCardLiability {
    /// The ID of the account that this liability belongs to.
    #[serde(rename = "accountId", deserialize_with = "Option::deserialize")]
    pub account_id: Option<String>,
    /// The various interest rates that apply to the account. APR information is not provided by all card issuers; if APR data is not available, this array will be empty.
    #[serde(rename = "aprs")]
    pub aprs: Vec<models::Apr>,
    /// true if a payment is currently overdue. Availability for this field is limited.
    #[serde(rename = "isOverdue", deserialize_with = "Option::deserialize")]
    pub is_overdue: Option<bool>,
    /// The amount of the last payment.
    #[serde(rename = "lastPaymentAmount", deserialize_with = "Option::deserialize")]
    pub last_payment_amount: Option<f64>,
    /// The date of the last payment. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD). Availability for this field is limited.
    #[serde(rename = "lastPaymentDate", deserialize_with = "Option::deserialize")]
    pub last_payment_date: Option<chrono::NaiveDate>,
    /// The total amount owed as of the last statement issued
    #[serde(rename = "lastStatementBalance", deserialize_with = "Option::deserialize")]
    pub last_statement_balance: Option<f64>,
    /// The date of the last statement. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
    #[serde(rename = "lastStatementIssueDate", deserialize_with = "Option::deserialize")]
    pub last_statement_issue_date: Option<chrono::NaiveDate>,
    /// The minimum payment due for the next billing cycle.
    #[serde(rename = "minimumPaymentAmount", deserialize_with = "Option::deserialize")]
    pub minimum_payment_amount: Option<f64>,
    /// The due date for the next payment. The due date is `null` if a payment is not expected. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
    #[serde(rename = "nextPaymentDueDate", deserialize_with = "Option::deserialize")]
    pub next_payment_due_date: Option<chrono::NaiveDate>,
}

impl CreditCardLiability {
    /// An object representing a credit card account.
    pub fn new(account_id: Option<String>, aprs: Vec<models::Apr>, is_overdue: Option<bool>, last_payment_amount: Option<f64>, last_payment_date: Option<chrono::NaiveDate>, last_statement_balance: Option<f64>, last_statement_issue_date: Option<chrono::NaiveDate>, minimum_payment_amount: Option<f64>, next_payment_due_date: Option<chrono::NaiveDate>) -> CreditCardLiability {
        CreditCardLiability {
            account_id,
            aprs,
            is_overdue,
            last_payment_amount,
            last_payment_date,
            last_statement_balance,
            last_statement_issue_date,
            minimum_payment_amount,
            next_payment_due_date,
        }
    }
}

