/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DebtSecurityEntity : Information about the debt security specific to the type of security
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DebtSecurityEntity {
    /// Bond Maturity date
    #[serde(rename = "bondMaturityDate", skip_serializing_if = "Option::is_none")]
    pub bond_maturity_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Next call date
    #[serde(rename = "callDate", skip_serializing_if = "Option::is_none")]
    pub call_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Bond call price
    #[serde(rename = "callPrice", skip_serializing_if = "Option::is_none")]
    pub call_price: Option<f64>,
    /// Type of next call
    #[serde(rename = "callType", skip_serializing_if = "Option::is_none")]
    pub call_type: Option<CallType>,
    /// Maturity date for next coupon
    #[serde(rename = "couponDate", skip_serializing_if = "Option::is_none")]
    pub coupon_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// When coupons mature
    #[serde(rename = "couponMatureFrequency", skip_serializing_if = "Option::is_none")]
    pub coupon_mature_frequency: Option<CouponMatureFrequency>,
    /// Bond coupon rate for next closest call date
    #[serde(rename = "couponRate", skip_serializing_if = "Option::is_none")]
    pub coupon_rate: Option<f64>,
    /// Classification of debt
    #[serde(rename = "debtClass", skip_serializing_if = "Option::is_none")]
    pub debt_class: Option<DebtClass>,
    /// Debt type
    #[serde(rename = "debtType", skip_serializing_if = "Option::is_none")]
    pub debt_type: Option<DebtType>,
    /// Par value amount
    #[serde(rename = "parValue", skip_serializing_if = "Option::is_none")]
    pub par_value: Option<f64>,
    /// Yield to next call
    #[serde(rename = "yieldToCall", skip_serializing_if = "Option::is_none")]
    pub yield_to_call: Option<f64>,
    /// Yield to maturity
    #[serde(rename = "yieldToMaturity", skip_serializing_if = "Option::is_none")]
    pub yield_to_maturity: Option<f64>,
}

impl DebtSecurityEntity {
    /// Information about the debt security specific to the type of security
    pub fn new() -> DebtSecurityEntity {
        DebtSecurityEntity {
            bond_maturity_date: None,
            call_date: None,
            call_price: None,
            call_type: None,
            coupon_date: None,
            coupon_mature_frequency: None,
            coupon_rate: None,
            debt_class: None,
            debt_type: None,
            par_value: None,
            yield_to_call: None,
            yield_to_maturity: None,
        }
    }
}
/// Type of next call
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CallType {
    #[serde(rename = "CALL")]
    Call,
    #[serde(rename = "PUT")]
    Put,
    #[serde(rename = "PREFUND")]
    Prefund,
    #[serde(rename = "MATURITY")]
    Maturity,
}

impl Default for CallType {
    fn default() -> CallType {
        Self::Call
    }
}
/// When coupons mature
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CouponMatureFrequency {
    #[serde(rename = "MONTHLY")]
    Monthly,
    #[serde(rename = "QUARTERLY")]
    Quarterly,
    #[serde(rename = "SEMIANNUAL")]
    Semiannual,
    #[serde(rename = "ANNUAL")]
    Annual,
    #[serde(rename = "OTHER")]
    Other,
}

impl Default for CouponMatureFrequency {
    fn default() -> CouponMatureFrequency {
        Self::Monthly
    }
}
/// Classification of debt
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DebtClass {
    #[serde(rename = "TREASURY")]
    Treasury,
    #[serde(rename = "MUNICIPAL")]
    Municipal,
    #[serde(rename = "CORPORATE")]
    Corporate,
    #[serde(rename = "OTHER")]
    Other,
}

impl Default for DebtClass {
    fn default() -> DebtClass {
        Self::Treasury
    }
}
/// Debt type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DebtType {
    #[serde(rename = "ASSET")]
    Asset,
    #[serde(rename = "COUPON")]
    Coupon,
}

impl Default for DebtType {
    fn default() -> DebtType {
        Self::Asset
    }
}

