/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnrichedTransaction1 {
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<String>>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    #[serde(rename = "locationStructured", skip_serializing_if = "Option::is_none")]
    pub location_structured: Option<Box<models::LocationStructuredPublic>>,
    #[serde(rename = "logo", skip_serializing_if = "Option::is_none")]
    pub logo: Option<String>,
    #[serde(rename = "mcc", skip_serializing_if = "Option::is_none")]
    pub mcc: Option<Vec<i32>>,
    #[serde(rename = "merchant", skip_serializing_if = "Option::is_none")]
    pub merchant: Option<String>,
    #[serde(rename = "merchantId", skip_serializing_if = "Option::is_none")]
    pub merchant_id: Option<String>,
    #[serde(rename = "person", skip_serializing_if = "Option::is_none")]
    pub person: Option<String>,
    /// An enumeration.
    #[serde(rename = "recurrence", skip_serializing_if = "Option::is_none")]
    pub recurrence: Option<Recurrence>,
    #[serde(rename = "recurrenceGroup", skip_serializing_if = "Option::is_none")]
    pub recurrence_group: Option<Box<models::RecurrenceGroup>>,
    #[serde(rename = "recurrenceGroupId", skip_serializing_if = "Option::is_none")]
    pub recurrence_group_id: Option<String>,
    #[serde(rename = "transactionId")]
    pub transaction_id: String,
    /// An enumeration.
    #[serde(rename = "transactionType", skip_serializing_if = "Option::is_none")]
    pub transaction_type: Option<TransactionType>,
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
}

impl EnrichedTransaction1 {
    pub fn new(transaction_id: String) -> EnrichedTransaction1 {
        EnrichedTransaction1 {
            labels: None,
            location: None,
            location_structured: None,
            logo: None,
            mcc: None,
            merchant: None,
            merchant_id: None,
            person: None,
            recurrence: None,
            recurrence_group: None,
            recurrence_group_id: None,
            transaction_id,
            transaction_type: None,
            website: None,
        }
    }
}
/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Recurrence {
    #[serde(rename = "recurring")]
    Recurring,
    #[serde(rename = "subscription")]
    Subscription,
    #[serde(rename = "one off")]
    OneOff,
}

impl Default for Recurrence {
    fn default() -> Recurrence {
        Self::Recurring
    }
}
/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransactionType {
    #[serde(rename = "business")]
    Business,
    #[serde(rename = "consumer")]
    Consumer,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for TransactionType {
    fn default() -> TransactionType {
        Self::Business
    }
}

