/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Holding : A securities holding at an institution.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Holding {
    /// The Plaid `account_id` associated with the holding.
    #[serde(rename = "accountId")]
    pub account_id: String,
    /// The total cost basis of the holding (e.g., the total amount spent to acquire all assets currently in the holding).
    #[serde(rename = "costBasis", deserialize_with = "Option::deserialize")]
    pub cost_basis: Option<f64>,
    /// The last price given by the institution for this security.
    #[serde(rename = "institutionPrice")]
    pub institution_price: f64,
    /// The date at which `institution_price` was current.
    #[serde(rename = "institutionPriceAsOf", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub institution_price_as_of: Option<Option<chrono::NaiveDate>>,
    /// Date and time at which `institution_price` was current, in ISO 8601 format (YYYY-MM-DDTHH:mm:ssZ).  This field is returned for select financial institutions and comes as provided by the institution. It may contain default time values (such as 00:00:00). 
    #[serde(rename = "institutionPriceDatetime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub institution_price_datetime: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The value of the holding, as reported by the institution.
    #[serde(rename = "institutionValue")]
    pub institution_value: f64,
    /// The ISO-4217 currency code of the holding. Always `null` if `unofficial_currency_code` is non-`null`.
    #[serde(rename = "isoCurrencyCode", deserialize_with = "Option::deserialize")]
    pub iso_currency_code: Option<String>,
    /// The total quantity of the asset held, as reported by the financial institution. If the security is an option, `quantity` will reflect the total number of options (typically the number of contracts multiplied by 100), not the number of contracts.
    #[serde(rename = "quantity")]
    pub quantity: f64,
    /// The Plaid `security_id` associated with the holding. Security data is not specific to a user's account; any user who held the same security at the same financial institution at the same time would have identical security data. The `security_id` for the same security will typically be the same across different institutions, but this is not guaranteed. The `security_id` does not typically change, but may change if inherent details of the security change due to a corporate action, for example, in the event of a ticker symbol change or CUSIP change.
    #[serde(rename = "securityId")]
    pub security_id: String,
    /// The unofficial currency code associated with the holding. Always `null` if `iso_currency_code` is non-`null`. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.  See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `iso_currency_code`s. 
    #[serde(rename = "unofficialCurrencyCode", deserialize_with = "Option::deserialize")]
    pub unofficial_currency_code: Option<String>,
    /// The total quantity of vested assets held, as reported by the financial institution. Vested assets are only associated with [equities](https://plaid.com/docs/api/products/investments/#investments-holdings-get-response-securities-type).
    #[serde(rename = "vestedQuantity", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vested_quantity: Option<Option<f64>>,
    /// The value of the vested holdings as reported by the institution.
    #[serde(rename = "vestedValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vested_value: Option<Option<f64>>,
}

impl Holding {
    /// A securities holding at an institution.
    pub fn new(account_id: String, cost_basis: Option<f64>, institution_price: f64, institution_value: f64, iso_currency_code: Option<String>, quantity: f64, security_id: String, unofficial_currency_code: Option<String>) -> Holding {
        Holding {
            account_id,
            cost_basis,
            institution_price,
            institution_price_as_of: None,
            institution_price_datetime: None,
            institution_value,
            iso_currency_code,
            quantity,
            security_id,
            unofficial_currency_code,
            vested_quantity: None,
            vested_value: None,
        }
    }
}

