/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LoanAccount : Loan Account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoanAccount {
    /// Long-term persistent identity of the account. Not an account number. This identity must be unique to the owning institution.
    #[serde(rename = "accountId")]
    pub account_id: String,
    /// Account display number for the end user’s handle at owning institution. This is to be displayed by the Interface Provider.
    #[serde(rename = "accountNumberDisplay", skip_serializing_if = "Option::is_none")]
    pub account_number_display: Option<String>,
    /// The type of an account. For instance, CHECKING, SAVINGS, 401K, etc.
    #[serde(rename = "accountType", skip_serializing_if = "Option::is_none")]
    pub account_type: Option<String>,
    /// ASSET (positive transaction amount increases balance), LIABILITY (positive transaction amount decreases balance)
    #[serde(rename = "balanceType", skip_serializing_if = "Option::is_none")]
    pub balance_type: Option<BalanceType>,
    #[serde(rename = "compoundingPeriod", skip_serializing_if = "Option::is_none")]
    pub compounding_period: Option<CompoundingPeriod>,
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Box<models::CurrencyEntity>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::ErrorEntity>>,
    #[serde(rename = "fiAttributes", skip_serializing_if = "Option::is_none")]
    pub fi_attributes: Option<Vec<models::FiAttributeEntity>>,
    /// Interest Rate of Account
    #[serde(rename = "interestRate", skip_serializing_if = "Option::is_none")]
    pub interest_rate: Option<f64>,
    /// Date of account’s interest rate
    #[serde(rename = "interestRateAsOf", skip_serializing_if = "Option::is_none")]
    pub interest_rate_as_of: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The type of interest rate. FIXED or VARIABLE.
    #[serde(rename = "interestRateType", skip_serializing_if = "Option::is_none")]
    pub interest_rate_type: Option<InterestRateType>,
    /// Date that last transaction occurred on account
    #[serde(rename = "lastActivityDate", skip_serializing_if = "Option::is_none")]
    pub last_activity_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The line of business, such as consumer, consumer joint, small business, corporate, etc.
    #[serde(rename = "lineOfBusiness", skip_serializing_if = "Option::is_none")]
    pub line_of_business: Option<String>,
    /// Term of loan in months
    #[serde(rename = "loanTerm", skip_serializing_if = "Option::is_none")]
    pub loan_term: Option<i32>,
    /// Maturity date is required for CDs
    #[serde(rename = "maturityDate", skip_serializing_if = "Option::is_none")]
    pub maturity_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// MICR Number
    #[serde(rename = "micrNumber", skip_serializing_if = "Option::is_none")]
    pub micr_number: Option<String>,
    /// Name given by the user. Used in UIs to assist in account selection
    #[serde(rename = "nickname", skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
    /// Loan origination date
    #[serde(rename = "originatingDate", skip_serializing_if = "Option::is_none")]
    pub originating_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Long-term persistent identity of the parent account. This is used to group accounts.
    #[serde(rename = "parentAccountId", skip_serializing_if = "Option::is_none")]
    pub parent_account_id: Option<String>,
    #[serde(rename = "paymentFrequency", skip_serializing_if = "Option::is_none")]
    pub payment_frequency: Option<PaymentFrequency>,
    /// Previous Interest Rate of Account
    #[serde(rename = "priorInterestRate", skip_serializing_if = "Option::is_none")]
    pub prior_interest_rate: Option<f64>,
    /// Marketed product name for this account.  Used in UIs to assist in account selection          
    #[serde(rename = "productName", skip_serializing_if = "Option::is_none")]
    pub product_name: Option<String>,
    /// The status of an account.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Total number of payments
    #[serde(rename = "totalNumberOfPayments", skip_serializing_if = "Option::is_none")]
    pub total_number_of_payments: Option<i32>,
    /// Account is eligible for incoming transfers
    #[serde(rename = "transferIn", skip_serializing_if = "Option::is_none")]
    pub transfer_in: Option<bool>,
    /// Account is eligible for outgoing transfers
    #[serde(rename = "transferOut", skip_serializing_if = "Option::is_none")]
    pub transfer_out: Option<bool>,
}

impl LoanAccount {
    /// Loan Account
    pub fn new(account_id: String) -> LoanAccount {
        LoanAccount {
            account_id,
            account_number_display: None,
            account_type: None,
            balance_type: None,
            compounding_period: None,
            currency: None,
            description: None,
            error: None,
            fi_attributes: None,
            interest_rate: None,
            interest_rate_as_of: None,
            interest_rate_type: None,
            last_activity_date: None,
            line_of_business: None,
            loan_term: None,
            maturity_date: None,
            micr_number: None,
            nickname: None,
            originating_date: None,
            parent_account_id: None,
            payment_frequency: None,
            prior_interest_rate: None,
            product_name: None,
            status: None,
            total_number_of_payments: None,
            transfer_in: None,
            transfer_out: None,
        }
    }
}
/// ASSET (positive transaction amount increases balance), LIABILITY (positive transaction amount decreases balance)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BalanceType {
    #[serde(rename = "ASSET")]
    Asset,
    #[serde(rename = "LIABILITY")]
    Liability,
}

impl Default for BalanceType {
    fn default() -> BalanceType {
        Self::Asset
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CompoundingPeriod {
    #[serde(rename = "DAILY")]
    Daily,
    #[serde(rename = "WEEKLY")]
    Weekly,
    #[serde(rename = "BIWEEKLY")]
    Biweekly,
    #[serde(rename = "SEMIMONTHLY")]
    Semimonthly,
    #[serde(rename = "MONTHLY")]
    Monthly,
    #[serde(rename = "SEMIANNUALLY")]
    Semiannually,
    #[serde(rename = "ANNUALLY")]
    Annually,
}

impl Default for CompoundingPeriod {
    fn default() -> CompoundingPeriod {
        Self::Daily
    }
}
/// The type of interest rate. FIXED or VARIABLE.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InterestRateType {
    #[serde(rename = "FIXED")]
    Fixed,
    #[serde(rename = "VARIABLE")]
    Variable,
}

impl Default for InterestRateType {
    fn default() -> InterestRateType {
        Self::Fixed
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentFrequency {
    #[serde(rename = "DAILY")]
    Daily,
    #[serde(rename = "WEEKLY")]
    Weekly,
    #[serde(rename = "BIWEEKLY")]
    Biweekly,
    #[serde(rename = "SEMIMONTHLY")]
    Semimonthly,
    #[serde(rename = "MONTHLY")]
    Monthly,
    #[serde(rename = "SEMIANNUALLY")]
    Semiannually,
    #[serde(rename = "ANNUALLY")]
    Annually,
}

impl Default for PaymentFrequency {
    fn default() -> PaymentFrequency {
        Self::Daily
    }
}
/// The status of an account.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "OPEN")]
    Open,
    #[serde(rename = "CLOSED")]
    Closed,
    #[serde(rename = "PENDINGOPEN")]
    Pendingopen,
    #[serde(rename = "PENDINGCLOSE")]
    Pendingclose,
    #[serde(rename = "DELINQUENT")]
    Delinquent,
    #[serde(rename = "PAID")]
    Paid,
    #[serde(rename = "NEGATIVECURRENTBALANCE")]
    Negativecurrentbalance,
}

impl Default for Status {
    fn default() -> Status {
        Self::Open
    }
}

