/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LoanTransaction : Loan Transaction
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoanTransaction {
    /// Corresponds to AccountId in Account
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    /// The amount of money in the account currency.  If balanceType is `ASSET`:    1. If `debitCreditMemo` = `DEBIT`, sign is \"+\" or not present   2. If `CREDIT`, sign is \"-\"  If balanceType is `LIABILITY`:    1. If `debitCreditMemo` = `DEBIT`, sign is \"-\"   2. If `CREDIT`, sign is \"+\" or not present
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
    /// Transaction category, preferably MCC or SIC.
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Akoya will ensure that this is correctly populated with one of DEBIT or CREDIT and matches the sign of the status field.
    #[serde(rename = "debitCreditMemo", skip_serializing_if = "Option::is_none")]
    pub debit_credit_memo: Option<DebitCreditMemo>,
    /// The description of the transaction
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Array of FI-specific attributes
    #[serde(rename = "fiAttributes", skip_serializing_if = "Option::is_none")]
    pub fi_attributes: Option<Vec<models::FiAttributeEntity>>,
    /// The amount of money in the foreign currency
    #[serde(rename = "foreignAmount", skip_serializing_if = "Option::is_none")]
    pub foreign_amount: Option<f64>,
    /// The ISO 4217 code of the foreign currency
    #[serde(rename = "foreignCurrency", skip_serializing_if = "Option::is_none")]
    pub foreign_currency: Option<String>,
    /// Array of image identifiers (unique to transaction) used to retrieve images of check or transaction receipt.
    #[serde(rename = "imageIds", skip_serializing_if = "Option::is_none")]
    pub image_ids: Option<Vec<String>>,
    /// Breakdown of the transaction details
    #[serde(rename = "lineItem", skip_serializing_if = "Option::is_none")]
    pub line_item: Option<Vec<models::LineItem>>,
    /// Links (unique to this Transaction) used to retrieve images of checks or transaction receipts, or invoke other APIs
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<models::HateoasLink>>,
    /// Secondary transaction description
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "paymentDetails", skip_serializing_if = "Option::is_none")]
    pub payment_details: Option<Box<models::PaymentDetails>>,
    /// The date and time that the transaction was posted to the account. If not provided then TransactionTimestamp can be used as PostedTimeStamp.
    #[serde(rename = "postedTimestamp", skip_serializing_if = "Option::is_none")]
    pub posted_timestamp: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// A tracking reference identifier
    #[serde(rename = "reference", skip_serializing_if = "Option::is_none")]
    pub reference: Option<String>,
    /// Akoya ensures that this field is populated for all transactions which are reversals, otherwise it is null. Either way it is always present.  For reverse postings, the identity of the transaction being reversed. For the correction transaction, the identity of the reversing post. For credit card posting transactions, the identity of the authorization transaction.
    #[serde(rename = "referenceTransactionId", skip_serializing_if = "Option::is_none")]
    pub reference_transaction_id: Option<String>,
    /// AUTHORIZATION, MEMO, PENDING, or POSTED
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Transaction category detail
    #[serde(rename = "subCategory", skip_serializing_if = "Option::is_none")]
    pub sub_category: Option<String>,
    /// Long term persistent identity of the transaction (unique to account). Transaction IDs should:    1. be the same for pending and posted   2. be different for reversed transactions   3. `referenceTransactionId` should be present for reversed transactions'
    #[serde(rename = "transactionId", skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<String>,
    /// The date and time that the transaction was added to the server backend systems.  Akoya ensures that this field is populated for all transactions to which it applies, otherwise it is null. Either way it is always present.
    #[serde(rename = "transactionTimestamp", skip_serializing_if = "Option::is_none")]
    pub transaction_timestamp: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// LoanTransaction Type
    #[serde(rename = "transactionType", skip_serializing_if = "Option::is_none")]
    pub transaction_type: Option<TransactionType>,
}

impl LoanTransaction {
    /// Loan Transaction
    pub fn new() -> LoanTransaction {
        LoanTransaction {
            account_id: None,
            amount: None,
            category: None,
            debit_credit_memo: None,
            description: None,
            fi_attributes: None,
            foreign_amount: None,
            foreign_currency: None,
            image_ids: None,
            line_item: None,
            links: None,
            memo: None,
            payment_details: None,
            posted_timestamp: None,
            reference: None,
            reference_transaction_id: None,
            status: None,
            sub_category: None,
            transaction_id: None,
            transaction_timestamp: None,
            transaction_type: None,
        }
    }
}
/// Akoya will ensure that this is correctly populated with one of DEBIT or CREDIT and matches the sign of the status field.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DebitCreditMemo {
    #[serde(rename = "DEBIT")]
    Debit,
    #[serde(rename = "CREDIT")]
    Credit,
}

impl Default for DebitCreditMemo {
    fn default() -> DebitCreditMemo {
        Self::Debit
    }
}
/// AUTHORIZATION, MEMO, PENDING, or POSTED
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "MEMO")]
    Memo,
    #[serde(rename = "POSTED")]
    Posted,
    #[serde(rename = "AUTHORIZATION")]
    Authorization,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}
/// LoanTransaction Type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransactionType {
    #[serde(rename = "ADJUSTMENT")]
    Adjustment,
    #[serde(rename = "FEE")]
    Fee,
    #[serde(rename = "INTEREST")]
    Interest,
    #[serde(rename = "PAYMENT")]
    Payment,
}

impl Default for TransactionType {
    fn default() -> TransactionType {
        Self::Adjustment
    }
}

