/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MortgageLiability : Contains details about a mortgage account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MortgageLiability {
    /// The ID of the account that this liability belongs to.
    #[serde(rename = "accountId")]
    pub account_id: String,
    /// The account number of the loan.
    #[serde(rename = "accountNumber", deserialize_with = "Option::deserialize")]
    pub account_number: Option<String>,
    /// The current outstanding amount charged for late payment.
    #[serde(rename = "currentLateFee", deserialize_with = "Option::deserialize")]
    pub current_late_fee: Option<f64>,
    /// Total amount held in escrow to pay taxes and insurance on behalf of the borrower.
    #[serde(rename = "escrowBalance", deserialize_with = "Option::deserialize")]
    pub escrow_balance: Option<f64>,
    /// Indicates whether the borrower has private mortgage insurance in effect.
    #[serde(rename = "hasPmi", deserialize_with = "Option::deserialize")]
    pub has_pmi: Option<bool>,
    /// Indicates whether the borrower will pay a penalty for early payoff of mortgage.
    #[serde(rename = "hasPrepaymentPenalty", deserialize_with = "Option::deserialize")]
    pub has_prepayment_penalty: Option<bool>,
    #[serde(rename = "interestRate")]
    pub interest_rate: models::MortgageInterestRate,
    /// The amount of the last payment.
    #[serde(rename = "lastPaymentAmount", deserialize_with = "Option::deserialize")]
    pub last_payment_amount: Option<f64>,
    /// The date of the last payment. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
    #[serde(rename = "lastPaymentDate", deserialize_with = "Option::deserialize")]
    pub last_payment_date: Option<chrono::NaiveDate>,
    /// Full duration of mortgage as at origination (e.g. `10 year`).
    #[serde(rename = "loanTerm", deserialize_with = "Option::deserialize")]
    pub loan_term: Option<String>,
    /// Description of the type of loan, for example `conventional`, `fixed`, or `variable`. This field is provided directly from the loan servicer and does not have an enumerated set of possible values.
    #[serde(rename = "loanTypeDescription", deserialize_with = "Option::deserialize")]
    pub loan_type_description: Option<String>,
    /// Original date on which mortgage is due in full. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
    #[serde(rename = "maturityDate", deserialize_with = "Option::deserialize")]
    pub maturity_date: Option<chrono::NaiveDate>,
    /// The amount of the next payment.
    #[serde(rename = "nextMonthlyPayment", deserialize_with = "Option::deserialize")]
    pub next_monthly_payment: Option<f64>,
    /// The due date for the next payment. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
    #[serde(rename = "nextPaymentDueDate", deserialize_with = "Option::deserialize")]
    pub next_payment_due_date: Option<chrono::NaiveDate>,
    /// The date on which the loan was initially lent. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
    #[serde(rename = "originationDate", deserialize_with = "Option::deserialize")]
    pub origination_date: Option<chrono::NaiveDate>,
    /// The original principal balance of the mortgage.
    #[serde(rename = "originationPrincipalAmount", deserialize_with = "Option::deserialize")]
    pub origination_principal_amount: Option<f64>,
    /// Amount of loan (principal + interest) past due for payment.
    #[serde(rename = "pastDueAmount", deserialize_with = "Option::deserialize")]
    pub past_due_amount: Option<f64>,
    #[serde(rename = "propertyAddress")]
    pub property_address: models::MortgagePropertyAddress,
    /// The year to date (YTD) interest paid.
    #[serde(rename = "ytdInterestPaid", deserialize_with = "Option::deserialize")]
    pub ytd_interest_paid: Option<f64>,
    /// The YTD principal paid.
    #[serde(rename = "ytdPrincipalPaid", deserialize_with = "Option::deserialize")]
    pub ytd_principal_paid: Option<f64>,
}

impl MortgageLiability {
    /// Contains details about a mortgage account.
    pub fn new(account_id: String, account_number: Option<String>, current_late_fee: Option<f64>, escrow_balance: Option<f64>, has_pmi: Option<bool>, has_prepayment_penalty: Option<bool>, interest_rate: models::MortgageInterestRate, last_payment_amount: Option<f64>, last_payment_date: Option<chrono::NaiveDate>, loan_term: Option<String>, loan_type_description: Option<String>, maturity_date: Option<chrono::NaiveDate>, next_monthly_payment: Option<f64>, next_payment_due_date: Option<chrono::NaiveDate>, origination_date: Option<chrono::NaiveDate>, origination_principal_amount: Option<f64>, past_due_amount: Option<f64>, property_address: models::MortgagePropertyAddress, ytd_interest_paid: Option<f64>, ytd_principal_paid: Option<f64>) -> MortgageLiability {
        MortgageLiability {
            account_id,
            account_number,
            current_late_fee,
            escrow_balance,
            has_pmi,
            has_prepayment_penalty,
            interest_rate,
            last_payment_amount,
            last_payment_date,
            loan_term,
            loan_type_description,
            maturity_date,
            next_monthly_payment,
            next_payment_due_date,
            origination_date,
            origination_principal_amount,
            past_due_amount,
            property_address,
            ytd_interest_paid,
            ytd_principal_paid,
        }
    }
}

