/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MutualFundSecurityEntity : Information about the mutual fund security specific to the type of security
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MutualFundSecurityEntity {
    /// Mutual fund type
    #[serde(rename = "mutualFundType", skip_serializing_if = "Option::is_none")]
    pub mutual_fund_type: Option<MutualFundType>,
    /// Reinvest capital gains
    #[serde(rename = "reinvestCapitalGains", skip_serializing_if = "Option::is_none")]
    pub reinvest_capital_gains: Option<bool>,
    /// Reinvest dividends
    #[serde(rename = "reinvestDividends", skip_serializing_if = "Option::is_none")]
    pub reinvest_dividends: Option<bool>,
    /// Units in the FI's street name, positive quantity
    #[serde(rename = "unitsStreet", skip_serializing_if = "Option::is_none")]
    pub units_street: Option<f64>,
    /// Units in user's name directly, positive  quantity
    #[serde(rename = "unitsUser", skip_serializing_if = "Option::is_none")]
    pub units_user: Option<f64>,
    /// Current yield reported as portion of the fund's assets
    #[serde(rename = "yield", skip_serializing_if = "Option::is_none")]
    pub r#yield: Option<f64>,
    /// As-of date for yield value
    #[serde(rename = "yieldAsOfDate", skip_serializing_if = "Option::is_none")]
    pub yield_as_of_date: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl MutualFundSecurityEntity {
    /// Information about the mutual fund security specific to the type of security
    pub fn new() -> MutualFundSecurityEntity {
        MutualFundSecurityEntity {
            mutual_fund_type: None,
            reinvest_capital_gains: None,
            reinvest_dividends: None,
            units_street: None,
            units_user: None,
            r#yield: None,
            yield_as_of_date: None,
        }
    }
}
/// Mutual fund type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MutualFundType {
    #[serde(rename = "OPENEND")]
    Openend,
    #[serde(rename = "CLOSEEND")]
    Closeend,
    #[serde(rename = "OTHER")]
    Other,
}

impl Default for MutualFundType {
    fn default() -> MutualFundType {
        Self::Openend
    }
}

