/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OptionContract : Details about the option security.  For the Sandbox environment, this data is currently only available if the Item is using a [custom Sandbox user](https://plaid.com/docs/sandbox/user-custom/) and the `ticker` field of the custom security follows the [OCC Option Symbol](https://en.wikipedia.org/wiki/Option_symbol#The_OCC_Option_Symbol) standard with no spaces. For an example of simulating this in Sandbox, see the [custom Sandbox GitHub](https://github.com/plaid/sandbox-custom-users).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptionContract {
    /// The type of this option contract. It is one of:  `put`: for Put option contracts  `call`: for Call option contracts
    #[serde(rename = "contractType")]
    pub contract_type: String,
    /// The expiration date for this option contract, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "expirationDate")]
    pub expiration_date: chrono::NaiveDate,
    /// The strike price for this option contract, per share of security.
    #[serde(rename = "strikePrice")]
    pub strike_price: f64,
    /// The ticker of the underlying security for this option contract.
    #[serde(rename = "underlyingSecurityTicker")]
    pub underlying_security_ticker: String,
}

impl OptionContract {
    /// Details about the option security.  For the Sandbox environment, this data is currently only available if the Item is using a [custom Sandbox user](https://plaid.com/docs/sandbox/user-custom/) and the `ticker` field of the custom security follows the [OCC Option Symbol](https://en.wikipedia.org/wiki/Option_symbol#The_OCC_Option_Symbol) standard with no spaces. For an example of simulating this in Sandbox, see the [custom Sandbox GitHub](https://github.com/plaid/sandbox-custom-users).
    pub fn new(contract_type: String, expiration_date: chrono::NaiveDate, strike_price: f64, underlying_security_ticker: String) -> OptionContract {
        OptionContract {
            contract_type,
            expiration_date,
            strike_price,
            underlying_security_ticker,
        }
    }
}

