/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Owner : Data returned from the financial institution about the owner or owners of an account. Only the `names` array must be non-empty.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Owner {
    /// Data about the various addresses associated with the account by the financial institution. May be an empty array if no relevant information is returned from the financial institution.
    #[serde(rename = "addresses")]
    pub addresses: Vec<models::Address>,
    /// A list of email addresses associated with the account by the financial institution. May be an empty array if no relevant information is returned from the financial institution.
    #[serde(rename = "emails")]
    pub emails: Vec<models::Email>,
    /// A list of names associated with the account by the financial institution. In the case of a joint account, Plaid will make a best effort to report the names of all account holders.  If an Item contains multiple accounts with different owner names, some institutions will report all names associated with the Item in each account's `names` array.
    #[serde(rename = "names")]
    pub names: Vec<String>,
    /// A list of phone numbers associated with the account by the financial institution. May be an empty array if no relevant information is returned from the financial institution.
    #[serde(rename = "phoneNumbers")]
    pub phone_numbers: Vec<models::PhoneNumber>,
}

impl Owner {
    /// Data returned from the financial institution about the owner or owners of an account. Only the `names` array must be non-empty.
    pub fn new(addresses: Vec<models::Address>, emails: Vec<models::Email>, names: Vec<String>, phone_numbers: Vec<models::PhoneNumber>) -> Owner {
        Owner {
            addresses,
            emails,
            names,
            phone_numbers,
        }
    }
}

