/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentDetails : Payment details for some transactions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentDetails {
    /// The amount of payment applied to escrow
    #[serde(rename = "escrowAmount", skip_serializing_if = "Option::is_none")]
    pub escrow_amount: Option<f64>,
    /// The amount of payment applied to fees
    #[serde(rename = "feesAmount", skip_serializing_if = "Option::is_none")]
    pub fees_amount: Option<f64>,
    /// The amount of payment applied to life/health/accident insurance on the loan
    #[serde(rename = "insuranceAmount", skip_serializing_if = "Option::is_none")]
    pub insurance_amount: Option<f64>,
    /// The amount of payment applied to interest
    #[serde(rename = "interestAmount", skip_serializing_if = "Option::is_none")]
    pub interest_amount: Option<f64>,
    /// The amount of payment applied to PMI
    #[serde(rename = "pmiAmount", skip_serializing_if = "Option::is_none")]
    pub pmi_amount: Option<f64>,
    /// The amount of payment applied to principal
    #[serde(rename = "principalAmount", skip_serializing_if = "Option::is_none")]
    pub principal_amount: Option<f64>,
}

impl PaymentDetails {
    /// Payment details for some transactions
    pub fn new() -> PaymentDetails {
        PaymentDetails {
            escrow_amount: None,
            fees_amount: None,
            insurance_amount: None,
            interest_amount: None,
            pmi_amount: None,
            principal_amount: None,
        }
    }
}

