/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentMeta : Transaction information specific to inter-bank transfers. If the transaction was not an inter-bank transfer, all fields will be `null`.  If the `transactions` object was returned by a Transactions endpoint such as `/transactions/sync` or `/transactions/get`, the `payment_meta` key will always appear, but no data elements are guaranteed. If the `transactions` object was returned by an Assets endpoint such as `/asset_report/get/` or `/asset_report/pdf/get`, this field will only appear in an Asset Report with Insights.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentMeta {
    /// The party initiating a wire transfer. Will be `null` if the transaction is not a wire transfer.
    #[serde(rename = "byOrderOf", deserialize_with = "Option::deserialize")]
    pub by_order_of: Option<String>,
    /// For transfers, the party that is receiving the transaction.
    #[serde(rename = "payee", deserialize_with = "Option::deserialize")]
    pub payee: Option<String>,
    /// For transfers, the party that is paying the transaction.
    #[serde(rename = "payer", deserialize_with = "Option::deserialize")]
    pub payer: Option<String>,
    /// The type of transfer, e.g. 'ACH'
    #[serde(rename = "paymentMethod", deserialize_with = "Option::deserialize")]
    pub payment_method: Option<String>,
    /// The name of the payment processor
    #[serde(rename = "paymentProcessor", deserialize_with = "Option::deserialize")]
    pub payment_processor: Option<String>,
    /// The ACH PPD ID for the payer.
    #[serde(rename = "ppdId", deserialize_with = "Option::deserialize")]
    pub ppd_id: Option<String>,
    /// The payer-supplied description of the transfer.
    #[serde(rename = "reason", deserialize_with = "Option::deserialize")]
    pub reason: Option<String>,
    /// The transaction reference number supplied by the financial institution.
    #[serde(rename = "referenceNumber", deserialize_with = "Option::deserialize")]
    pub reference_number: Option<String>,
}

impl PaymentMeta {
    /// Transaction information specific to inter-bank transfers. If the transaction was not an inter-bank transfer, all fields will be `null`.  If the `transactions` object was returned by a Transactions endpoint such as `/transactions/sync` or `/transactions/get`, the `payment_meta` key will always appear, but no data elements are guaranteed. If the `transactions` object was returned by an Assets endpoint such as `/asset_report/get/` or `/asset_report/pdf/get`, this field will only appear in an Asset Report with Insights.
    pub fn new(by_order_of: Option<String>, payee: Option<String>, payer: Option<String>, payment_method: Option<String>, payment_processor: Option<String>, ppd_id: Option<String>, reason: Option<String>, reference_number: Option<String>) -> PaymentMeta {
        PaymentMeta {
            by_order_of,
            payee,
            payer,
            payment_method,
            payment_processor,
            ppd_id,
            reason,
            reference_number,
        }
    }
}

