/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProfileAddress : The legal address associated with the Profile.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileAddress {
    /// The first line of the address.
    #[serde(rename = "line1")]
    pub line1: String,
    /// The second line of the address.
    #[serde(rename = "line2", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub line2: Option<Option<String>>,
    /// The city.
    #[serde(rename = "city")]
    pub city: String,
    /// The state or province.
    #[serde(rename = "state")]
    pub state: String,
    /// The postal code or zip code.
    #[serde(rename = "postalCode")]
    pub postal_code: String,
    /// ISO 3166-1 alpha-3 country code.  - `USA` - United States of America 
    #[serde(rename = "countryCode")]
    pub country_code: CountryCode,
}

impl ProfileAddress {
    /// The legal address associated with the Profile.
    pub fn new(line1: String, city: String, state: String, postal_code: String, country_code: CountryCode) -> ProfileAddress {
        ProfileAddress {
            line1,
            line2: None,
            city,
            state,
            postal_code,
            country_code,
        }
    }
}
/// ISO 3166-1 alpha-3 country code.  - `USA` - United States of America 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CountryCode {
    #[serde(rename = "USA")]
    Usa,
}

impl Default for CountryCode {
    fn default() -> CountryCode {
        Self::Usa
    }
}

