/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RemoteFinicityAccountDocumentsApiFinicityComAggregationV1CustomersCustomerIdInstitutionLoginsInstitutionLoginIdAccountsBodyDetail : Additional customer account details. Not all data points will return for each account type. You can see the account type that each data point will return for in descriptions. The data point are also subject to availability by the institution.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoteFinicityAccountDocumentsApiFinicityComAggregationV1CustomersCustomerIdInstitutionLoginsInstitutionLoginIdAccountsBodyDetail {
    /// (Investment) After-tax amount of total balance
    #[serde(rename = "afterTaxAmount", skip_serializing_if = "Option::is_none")]
    pub after_tax_amount: Option<f64>,
    /// (Mortgage/Loan) Enrolled in autopay (T/F or Y/N).
    #[serde(rename = "autoPayEnrolled", skip_serializing_if = "Option::is_none")]
    pub auto_pay_enrolled: Option<String>,
    /// (Checking/Savings/CD/MoneyMarket) and (Mortgage/Loan) The available balance (typically the current balance with adjustments for any pending transactions)
    #[serde(rename = "availableBalanceAmount", skip_serializing_if = "Option::is_none")]
    pub available_balance_amount: Option<f64>,
    /// (Investment) Amount available for cash withdrawal
    #[serde(rename = "availableCashBalance", skip_serializing_if = "Option::is_none")]
    pub available_cash_balance: Option<f64>,
    /// (Mortgage/Loan) Balloon payment amount
    #[serde(rename = "balloonAmount", skip_serializing_if = "Option::is_none")]
    pub balloon_amount: Option<f64>,
    /// (Investment) Money available to buy securities
    #[serde(rename = "buyPower", skip_serializing_if = "Option::is_none")]
    pub buy_power: Option<f64>,
    /// Cash account allowed indicator (true / false)
    #[serde(rename = "cashAccountAllowed", skip_serializing_if = "Option::is_none")]
    pub cash_account_allowed: Option<bool>,
    /// (Credit Card/Line Of Credit) Currently available cash advance
    #[serde(rename = "cashAdvanceAvailableAmount", skip_serializing_if = "Option::is_none")]
    pub cash_advance_available_amount: Option<f64>,
    /// (Credit Card/Line Of Credit) Balance of current cash advance
    #[serde(rename = "cashAdvanceBalance", skip_serializing_if = "Option::is_none")]
    pub cash_advance_balance: Option<f64>,
    /// (Credit Card/Line Of Credit) Interest rate for cash advances
    #[serde(rename = "cashAdvanceInterestRate", skip_serializing_if = "Option::is_none")]
    pub cash_advance_interest_rate: Option<f64>,
    /// (Credit Card/Line Of Credit) Maximum cash advance amount
    #[serde(rename = "cashAdvanceMaxAmount", skip_serializing_if = "Option::is_none")]
    pub cash_advance_max_amount: Option<f64>,
    /// (Investment) Cash balance of account
    #[serde(rename = "cashBalanceAmount", skip_serializing_if = "Option::is_none")]
    pub cash_balance_amount: Option<f64>,
    /// (Mortgage/Loan) Collateral on loan
    #[serde(rename = "collateral", skip_serializing_if = "Option::is_none")]
    pub collateral: Option<String>,
    /// (Investment) Total year to date contributions
    #[serde(rename = "contribTotalYtd", skip_serializing_if = "Option::is_none")]
    pub contrib_total_ytd: Option<f64>,
    /// (Student Loan) The date the loan enters into repayment. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "convertToRepayment", skip_serializing_if = "Option::is_none")]
    pub convert_to_repayment: Option<i64>,
    /// (Credit Card/Line Of Credit) The available credit (typically the credit limit minus the current balance)
    #[serde(rename = "creditAvailableAmount", skip_serializing_if = "Option::is_none")]
    pub credit_available_amount: Option<f64>,
    /// (Credit Card/Line Of Credit) The account's credit limit
    #[serde(rename = "creditMaxAmount", skip_serializing_if = "Option::is_none")]
    pub credit_max_amount: Option<f64>,
    /// (Credit Card/Line Of Credit) and (Investment) Current balance
    #[serde(rename = "currentBalance", skip_serializing_if = "Option::is_none")]
    pub current_balance: Option<f64>,
    /// (Investment) Current loan balance
    #[serde(rename = "currentLoanBalance", skip_serializing_if = "Option::is_none")]
    pub current_loan_balance: Option<f64>,
    /// (Mortgage/Loan) Current school
    #[serde(rename = "currentSchool", skip_serializing_if = "Option::is_none")]
    pub current_school: Option<String>,
    /// (All Account Types) Most recent date of the following information. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "dateAsOf", skip_serializing_if = "Option::is_none")]
    pub date_as_of: Option<i64>,
    /// (Student Loan) The number of days past a due date that a payment should have been made
    #[serde(rename = "daysDelinquent", skip_serializing_if = "Option::is_none")]
    pub days_delinquent: Option<i32>,
    /// (Mortgage/Loan) Description of loan
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// (Investment) Employer matched contributions
    #[serde(rename = "empMatchAmount", skip_serializing_if = "Option::is_none")]
    pub emp_match_amount: Option<f64>,
    /// (Investment) Employer pretax contribution amount
    #[serde(rename = "empPretaxContribAmount", skip_serializing_if = "Option::is_none")]
    pub emp_pretax_contrib_amount: Option<f64>,
    /// (Investment) Employer pretax contribution amount year to date
    #[serde(rename = "empPretaxContribAmountYtd", skip_serializing_if = "Option::is_none")]
    pub emp_pretax_contrib_amount_ytd: Option<f64>,
    /// (Mortgage/Loan) Ending balance
    #[serde(rename = "endingBalanceAmount", skip_serializing_if = "Option::is_none")]
    pub ending_balance_amount: Option<f64>,
    /// (Mortgage/Loan) The escrow balance
    #[serde(rename = "escrowBalance", skip_serializing_if = "Option::is_none")]
    pub escrow_balance: Option<f64>,
    /// (Student Loan) The expected date of the payoff date. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "expectedPayoffDate", skip_serializing_if = "Option::is_none")]
    pub expected_payoff_date: Option<i64>,
    /// (Student Loan) The total outstanding fees balance
    #[serde(rename = "feesBalance", skip_serializing_if = "Option::is_none")]
    pub fees_balance: Option<f64>,
    /// (Mortgage/Loan) First mortgage (F/Y)
    #[serde(rename = "firstMortgage", skip_serializing_if = "Option::is_none")]
    pub first_mortgage: Option<bool>,
    /// (Mortgage/Loan) First payment due date. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "firstPaymentDate", skip_serializing_if = "Option::is_none")]
    pub first_payment_date: Option<i64>,
    /// (Student Loan) The financial institution guarantor of the loan (who will pay the loan amount to the owner if the borrower defaults)
    #[serde(rename = "guarantor", skip_serializing_if = "Option::is_none")]
    pub guarantor: Option<String>,
    /// (Student Loan) Initial interest rate of loan
    #[serde(rename = "initialInterestRate", skip_serializing_if = "Option::is_none")]
    pub initial_interest_rate: Option<f64>,
    /// (Mortgage/Loan) Original loan amount
    #[serde(rename = "initialMlAmount", skip_serializing_if = "Option::is_none")]
    pub initial_ml_amount: Option<f64>,
    /// (Mortgage/Loan) Original date of loan. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "initialMlDate", skip_serializing_if = "Option::is_none")]
    pub initial_ml_date: Option<i64>,
    /// (Student Loan) The total outstanding interest balance
    #[serde(rename = "interestBalance", skip_serializing_if = "Option::is_none")]
    pub interest_balance: Option<f64>,
    /// (Mortgage/Loan) Interest paid since inception of loan (life to date)
    #[serde(rename = "interestPaidLtd", skip_serializing_if = "Option::is_none")]
    pub interest_paid_ltd: Option<f64>,
    /// (Mortgage/Loan) Period of interest
    #[serde(rename = "interestPeriod", skip_serializing_if = "Option::is_none")]
    pub interest_period: Option<String>,
    /// (Checking/Savings/CD/MoneyMarket) Interest earned in prior year
    #[serde(rename = "interestPriorYtdAmount", skip_serializing_if = "Option::is_none")]
    pub interest_prior_ytd_amount: Option<f64>,
    /// (Credit Card/Line Of Credit) and (Mortgage/Loan) The account's current interest rate
    #[serde(rename = "interestRate", skip_serializing_if = "Option::is_none")]
    pub interest_rate: Option<String>,
    /// (Mortgage/Loan) Type of interest rate
    #[serde(rename = "interestRateType", skip_serializing_if = "Option::is_none")]
    pub interest_rate_type: Option<String>,
    /// (Student Loan) The indication of the presence of an interest subsidy (i.e. subsidized)
    #[serde(rename = "interestSubsidyType", skip_serializing_if = "Option::is_none")]
    pub interest_subsidy_type: Option<String>,
    /// (Checking/Savings/CD/MoneyMarket) Interest accrued year-to-date
    #[serde(rename = "interestYtdAmount", skip_serializing_if = "Option::is_none")]
    pub interest_ytd_amount: Option<f64>,
    /// (Credit Card/Line Of Credit) and (Mortgage/Loan) The amount received in the last payment
    #[serde(rename = "lastPaymentAmount", skip_serializing_if = "Option::is_none")]
    pub last_payment_amount: Option<f64>,
    /// (Credit Card/Line Of Credit) The date of the last payment. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "lastPaymentDate", skip_serializing_if = "Option::is_none")]
    pub last_payment_date: Option<i64>,
    /// (Mortgage/Loan) Due date of last payment. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "lastPaymentDueDate", skip_serializing_if = "Option::is_none")]
    pub last_payment_due_date: Option<i64>,
    /// (Mortgage/Loan) Amount towards escrow in last payment
    #[serde(rename = "lastPaymentEscrowAmount", skip_serializing_if = "Option::is_none")]
    pub last_payment_escrow_amount: Option<f64>,
    /// (Mortgage/Loan) Amount of interest in last payment
    #[serde(rename = "lastPaymentInterestAmount", skip_serializing_if = "Option::is_none")]
    pub last_payment_interest_amount: Option<f64>,
    /// (Mortgage/Loan) Amount of last fee in last payment
    #[serde(rename = "lastPaymentLastFeeAmount", skip_serializing_if = "Option::is_none")]
    pub last_payment_last_fee_amount: Option<f64>,
    /// (Mortgage/Loan) Amount of late charge in last payment
    #[serde(rename = "lastPaymentLateCharge", skip_serializing_if = "Option::is_none")]
    pub last_payment_late_charge: Option<f64>,
    /// (Mortgage/Loan) Amount towards principal in last payment
    #[serde(rename = "lastPaymentPrincipalAmount", skip_serializing_if = "Option::is_none")]
    pub last_payment_principal_amount: Option<f64>,
    /// (Mortgage/Loan) The date of the last payment. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "lastPaymentReceiveDate", skip_serializing_if = "Option::is_none")]
    pub last_payment_receive_date: Option<i64>,
    /// (Mortgage/Loan) Late fee charged
    #[serde(rename = "lateFeeAmount", skip_serializing_if = "Option::is_none")]
    pub late_fee_amount: Option<f64>,
    /// (Mortgage/Loan) Owner of loan
    #[serde(rename = "lender", skip_serializing_if = "Option::is_none")]
    pub lender: Option<String>,
    /// (Student Loan) The federal unique loan identifying number
    #[serde(rename = "loanAwardId", skip_serializing_if = "Option::is_none")]
    pub loan_award_id: Option<String>,
    /// (Mortgage/Loan) Frequency of payments (monthly, etc.)
    #[serde(rename = "loanPaymentFreq", skip_serializing_if = "Option::is_none")]
    pub loan_payment_freq: Option<String>,
    /// (Mortgage/Loan) Type of loan payment
    #[serde(rename = "loanPaymentType", skip_serializing_if = "Option::is_none")]
    pub loan_payment_type: Option<String>,
    /// (Investment) Interest rate of loan
    #[serde(rename = "loanRate", skip_serializing_if = "Option::is_none")]
    pub loan_rate: Option<f64>,
    /// (Student Loan) The repayment status phase (i.e. In School, Grace, Repayment, Deferment, Forbearance)
    #[serde(rename = "loanStatus", skip_serializing_if = "Option::is_none")]
    pub loan_status: Option<String>,
    /// (Student Loan) The end date of the current status. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "loanStatusEndDate", skip_serializing_if = "Option::is_none")]
    pub loan_status_end_date: Option<i64>,
    /// (Student Loan) The start date of the current status. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "loanStatusStartDate", skip_serializing_if = "Option::is_none")]
    pub loan_status_start_date: Option<i64>,
    /// (Mortgage/Loan) Type of loan term
    #[serde(rename = "loanTermType", skip_serializing_if = "Option::is_none")]
    pub loan_term_type: Option<String>,
    /// (Mortgage/Loan) Description of the mortgage or loan type
    #[serde(rename = "loanTypeDesc", skip_serializing_if = "Option::is_none")]
    pub loan_type_desc: Option<String>,
    /// (Student Loan) Loan fees paid year-to-date
    #[serde(rename = "loanYtdFeesPaid", skip_serializing_if = "Option::is_none")]
    pub loan_ytd_fees_paid: Option<f64>,
    /// (Student Loan) Loan interest paid year-to-date
    #[serde(rename = "loanYtdInterestPaid", skip_serializing_if = "Option::is_none")]
    pub loan_ytd_interest_paid: Option<f64>,
    /// (Student Loan) Loan principal paid year-to-date
    #[serde(rename = "loanYtdPrincipalPaid", skip_serializing_if = "Option::is_none")]
    pub loan_ytd_principal_paid: Option<f64>,
    /// Margin trading indicator (true / false)
    #[serde(rename = "marginAllowed", skip_serializing_if = "Option::is_none")]
    pub margin_allowed: Option<bool>,
    /// (Investment) Net interest earned after deducting interest paid out
    #[serde(rename = "marginBalance", skip_serializing_if = "Option::is_none")]
    pub margin_balance: Option<f64>,
    /// (Investment) Amount matched
    #[serde(rename = "matchAmount", skip_serializing_if = "Option::is_none")]
    pub match_amount: Option<f64>,
    /// (Checking/Savings/CD/MoneyMarket) Maturity date of account type. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "maturityDate", skip_serializing_if = "Option::is_none")]
    pub maturity_date: Option<i64>,
    /// (Investment) amount payable to an investor at maturity
    #[serde(rename = "maturityValueAmount", skip_serializing_if = "Option::is_none")]
    pub maturity_value_amount: Option<f64>,
    /// (Mortgage/Loan) Holder of the mortgage or loan
    #[serde(rename = "mlHolderName", skip_serializing_if = "Option::is_none")]
    pub ml_holder_name: Option<String>,
    /// (Mortgage/Loan) Minimum payment due
    #[serde(rename = "nextPayment", skip_serializing_if = "Option::is_none")]
    pub next_payment: Option<f64>,
    /// (Mortgage/Loan) Due date for the next payment. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "nextPaymentDate", skip_serializing_if = "Option::is_none")]
    pub next_payment_date: Option<i64>,
    /// (Mortgage/Loan) Amount of interest in next payment
    #[serde(rename = "nextPaymentInterestAmount", skip_serializing_if = "Option::is_none")]
    pub next_payment_interest_amount: Option<f64>,
    /// (Mortgage/Loan) Amount towards principal in next payment
    #[serde(rename = "nextPaymentPrincipalAmount", skip_serializing_if = "Option::is_none")]
    pub next_payment_principal_amount: Option<f64>,
    /// (Checking/Savings/CD/MoneyMarket) Date when account was opened. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "openDate", skip_serializing_if = "Option::is_none")]
    pub open_date: Option<i64>,
    /// (Student Loan) The original interest rate to which the loan was disbursed, in APY
    #[serde(rename = "originalInterestRate", skip_serializing_if = "Option::is_none")]
    pub original_interest_rate: Option<f64>,
    /// (Mortgage/Loan) Original date of loan maturity. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "originalMaturityDate", skip_serializing_if = "Option::is_none")]
    pub original_maturity_date: Option<i64>,
    /// (Mortgage/Loan) Original school
    #[serde(rename = "originalSchool", skip_serializing_if = "Option::is_none")]
    pub original_school: Option<String>,
    /// (Investment) Other nonvested amount
    #[serde(rename = "otherNonvestAmount", skip_serializing_if = "Option::is_none")]
    pub other_nonvest_amount: Option<f64>,
    /// (Investment) Other vested amount
    #[serde(rename = "otherVestAmount", skip_serializing_if = "Option::is_none")]
    pub other_vest_amount: Option<f64>,
    /// (Student Loan) The date the borrower graduated or dropped below half-time enrollment in school. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "outOfSchoolDate", skip_serializing_if = "Option::is_none")]
    pub out_of_school_date: Option<i64>,
    /// (Student Loan) Owner of the loan
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    /// (Credit Card/Line Of Credit) and (Mortgage/Loan) Balance past due
    #[serde(rename = "pastDueAmount", skip_serializing_if = "Option::is_none")]
    pub past_due_amount: Option<f64>,
    /// (Credit Card/Line Of Credit) Due date for the next payment. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "paymentDueDate", skip_serializing_if = "Option::is_none")]
    pub payment_due_date: Option<i64>,
    /// (Credit Card/Line Of Credit) and (Mortgage/Loan) Minimum payment due
    #[serde(rename = "paymentMinAmount", skip_serializing_if = "Option::is_none")]
    pub payment_min_amount: Option<f64>,
    /// (Mortgage/Loan) Number of payments made
    #[serde(rename = "paymentsMade", skip_serializing_if = "Option::is_none")]
    pub payments_made: Option<i32>,
    /// (Mortgage/Loan) Number of payments remaining before loan is paid off
    #[serde(rename = "paymentsRemaining", skip_serializing_if = "Option::is_none")]
    pub payments_remaining: Option<i32>,
    /// (Mortgage/Loan) The amount required to payoff the loan
    #[serde(rename = "payoffAmount", skip_serializing_if = "Option::is_none")]
    pub payoff_amount: Option<f64>,
    /// (Mortgage/Loan) Date of final payment. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "payoffAmountDate", skip_serializing_if = "Option::is_none")]
    pub payoff_amount_date: Option<i64>,
    /// (Checking/Savings/CD/MoneyMarket) Amount deposited in period
    #[serde(rename = "periodDepositAmount", skip_serializing_if = "Option::is_none")]
    pub period_deposit_amount: Option<f64>,
    /// End date of period. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "periodEndDate", skip_serializing_if = "Option::is_none")]
    pub period_end_date: Option<i64>,
    /// (Checking/Savings/CD/MoneyMarket) Interest accrued during the current period
    #[serde(rename = "periodInterestAmount", skip_serializing_if = "Option::is_none")]
    pub period_interest_amount: Option<f64>,
    /// (Checking/Savings/CD/MoneyMarket) The APY for the current period interest rate
    #[serde(rename = "periodInterestRate", skip_serializing_if = "Option::is_none")]
    pub period_interest_rate: Option<f64>,
    /// (Checking/Savings/CD/MoneyMarket) Start date of period. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "periodStartDate", skip_serializing_if = "Option::is_none")]
    pub period_start_date: Option<i64>,
    /// (Investment) Pre-tax amount of total balance
    #[serde(rename = "preTaxAmount", skip_serializing_if = "Option::is_none")]
    pub pre_tax_amount: Option<f64>,
    /// (Credit Card/Line Of Credit) Prior balance in last statement
    #[serde(rename = "previousBalance", skip_serializing_if = "Option::is_none")]
    pub previous_balance: Option<f64>,
    /// (Mortgage/Loan) The principal balance
    #[serde(rename = "principalBalance", skip_serializing_if = "Option::is_none")]
    pub principal_balance: Option<f64>,
    /// (Investment) Amount of balance for profit sharing
    #[serde(rename = "profitSharingAmount", skip_serializing_if = "Option::is_none")]
    pub profit_sharing_amount: Option<f64>,
    /// (Mortgage/Loan) Projected interest on the loan
    #[serde(rename = "projectedInterest", skip_serializing_if = "Option::is_none")]
    pub projected_interest: Option<f64>,
    /// (Mortgage/Loan) Recurring payment amount
    #[serde(rename = "recurringPaymentAmount", skip_serializing_if = "Option::is_none")]
    pub recurring_payment_amount: Option<f64>,
    /// (Student Loan) The number of months still outstanding on a loan
    #[serde(rename = "remainingTermOfMl", skip_serializing_if = "Option::is_none")]
    pub remaining_term_of_ml: Option<f64>,
    /// (Mortgage/Loan) Type of repayment plan for the student loan
    #[serde(rename = "repaymentPlan", skip_serializing_if = "Option::is_none")]
    pub repayment_plan: Option<String>,
    /// (Student Loan) The end date of the current repayment plan. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "repaymentPlanEndDate", skip_serializing_if = "Option::is_none")]
    pub repayment_plan_end_date: Option<i64>,
    /// (Student Loan) The start date of the current repayment plan. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "repaymentPlanStartDate", skip_serializing_if = "Option::is_none")]
    pub repayment_plan_start_date: Option<i64>,
    /// (Credit Card/Line Of Credit) Earned reward balance
    #[serde(rename = "rewardEarnedBalance", skip_serializing_if = "Option::is_none")]
    pub reward_earned_balance: Option<f32>,
    /// (Investment) Amount of balance rolled over from original account (401k, etc.)
    #[serde(rename = "rolloverAmount", skip_serializing_if = "Option::is_none")]
    pub rollover_amount: Option<f64>,
    /// (Investment) Life to date of money rolled over
    #[serde(rename = "rolloverLtd", skip_serializing_if = "Option::is_none")]
    pub rollover_ltd: Option<f64>,
    /// (Investment) Sum of short balance
    #[serde(rename = "shortBalance", skip_serializing_if = "Option::is_none")]
    pub short_balance: Option<f64>,
    /// (Credit Card/Line Of Credit) Balance of statement at close
    #[serde(rename = "statementCloseBalance", skip_serializing_if = "Option::is_none")]
    pub statement_close_balance: Option<f64>,
    /// (Mortgage/Loan) Date the statement closed. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://docs.finicity.com/endpoint-syntax-and-format/).
    #[serde(rename = "statementCloseDate", skip_serializing_if = "Option::is_none")]
    pub statement_close_date: Option<i64>,
    /// (Credit Card/Line Of Credit) Credit amount applied in statement period
    #[serde(rename = "statementCreditAmount", skip_serializing_if = "Option::is_none")]
    pub statement_credit_amount: Option<f64>,
    /// (Credit Card/Line Of Credit) End date of statement period. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "statementEndDate", skip_serializing_if = "Option::is_none")]
    pub statement_end_date: Option<i64>,
    /// (Credit Card/Line Of Credit) Finance amount of statement period
    #[serde(rename = "statementFinanceAmount", skip_serializing_if = "Option::is_none")]
    pub statement_finance_amount: Option<f64>,
    /// (Credit Card/Line Of Credit) Purchase amount of statement period
    #[serde(rename = "statementPurchaseAmount", skip_serializing_if = "Option::is_none")]
    pub statement_purchase_amount: Option<f64>,
    /// (Credit Card/Line Of Credit) Start date of statement period. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-finance-us/documentation/errors/best-practices/).
    #[serde(rename = "statementStartDate", skip_serializing_if = "Option::is_none")]
    pub statement_start_date: Option<i64>,
    /// (Mortgage/Loan) Length of loan in months
    #[serde(rename = "termOfMl", skip_serializing_if = "Option::is_none")]
    pub term_of_ml: Option<String>,
    /// (Student Loan) The total amount paid
    #[serde(rename = "totalAmountPaid", skip_serializing_if = "Option::is_none")]
    pub total_amount_paid: Option<f64>,
    /// (Mortgage/Loan/Student Loan) The total amount paid towards interest
    #[serde(rename = "totalInterestPaid", skip_serializing_if = "Option::is_none")]
    pub total_interest_paid: Option<f64>,
    /// (Mortgage/Loan/Student Loan) The total amount paid towards the principal balance
    #[serde(rename = "totalPrincipalPaid", skip_serializing_if = "Option::is_none")]
    pub total_principal_paid: Option<f64>,
    /// (Investment) Vested amount in account
    #[serde(rename = "vestedBalance", skip_serializing_if = "Option::is_none")]
    pub vested_balance: Option<f64>,
    /// (Student Loan) The interest rate of multiple interest rates and balances at the group level, in APY
    #[serde(rename = "weightedInterestRate", skip_serializing_if = "Option::is_none")]
    pub weighted_interest_rate: Option<f64>,
    /// (Mortgage/Loan) Insurance paid year-to-date
    #[serde(rename = "ytdInsurancePaid", skip_serializing_if = "Option::is_none")]
    pub ytd_insurance_paid: Option<f64>,
    /// (Mortgage/Loan) Interest paid year-to-date
    #[serde(rename = "ytdInterestPaid", skip_serializing_if = "Option::is_none")]
    pub ytd_interest_paid: Option<f64>,
    /// (Mortgage/Loan) Principal paid year-to-date
    #[serde(rename = "ytdPrincipalPaid", skip_serializing_if = "Option::is_none")]
    pub ytd_principal_paid: Option<f64>,
    /// (Mortgage/Loan) Tax paid year-to-date
    #[serde(rename = "ytdTaxPaid", skip_serializing_if = "Option::is_none")]
    pub ytd_tax_paid: Option<f64>,
}

impl RemoteFinicityAccountDocumentsApiFinicityComAggregationV1CustomersCustomerIdInstitutionLoginsInstitutionLoginIdAccountsBodyDetail {
    /// Additional customer account details. Not all data points will return for each account type. You can see the account type that each data point will return for in descriptions. The data point are also subject to availability by the institution.
    pub fn new() -> RemoteFinicityAccountDocumentsApiFinicityComAggregationV1CustomersCustomerIdInstitutionLoginsInstitutionLoginIdAccountsBodyDetail {
        RemoteFinicityAccountDocumentsApiFinicityComAggregationV1CustomersCustomerIdInstitutionLoginsInstitutionLoginIdAccountsBodyDetail {
            after_tax_amount: None,
            auto_pay_enrolled: None,
            available_balance_amount: None,
            available_cash_balance: None,
            balloon_amount: None,
            buy_power: None,
            cash_account_allowed: None,
            cash_advance_available_amount: None,
            cash_advance_balance: None,
            cash_advance_interest_rate: None,
            cash_advance_max_amount: None,
            cash_balance_amount: None,
            collateral: None,
            contrib_total_ytd: None,
            convert_to_repayment: None,
            credit_available_amount: None,
            credit_max_amount: None,
            current_balance: None,
            current_loan_balance: None,
            current_school: None,
            date_as_of: None,
            days_delinquent: None,
            description: None,
            emp_match_amount: None,
            emp_pretax_contrib_amount: None,
            emp_pretax_contrib_amount_ytd: None,
            ending_balance_amount: None,
            escrow_balance: None,
            expected_payoff_date: None,
            fees_balance: None,
            first_mortgage: None,
            first_payment_date: None,
            guarantor: None,
            initial_interest_rate: None,
            initial_ml_amount: None,
            initial_ml_date: None,
            interest_balance: None,
            interest_paid_ltd: None,
            interest_period: None,
            interest_prior_ytd_amount: None,
            interest_rate: None,
            interest_rate_type: None,
            interest_subsidy_type: None,
            interest_ytd_amount: None,
            last_payment_amount: None,
            last_payment_date: None,
            last_payment_due_date: None,
            last_payment_escrow_amount: None,
            last_payment_interest_amount: None,
            last_payment_last_fee_amount: None,
            last_payment_late_charge: None,
            last_payment_principal_amount: None,
            last_payment_receive_date: None,
            late_fee_amount: None,
            lender: None,
            loan_award_id: None,
            loan_payment_freq: None,
            loan_payment_type: None,
            loan_rate: None,
            loan_status: None,
            loan_status_end_date: None,
            loan_status_start_date: None,
            loan_term_type: None,
            loan_type_desc: None,
            loan_ytd_fees_paid: None,
            loan_ytd_interest_paid: None,
            loan_ytd_principal_paid: None,
            margin_allowed: None,
            margin_balance: None,
            match_amount: None,
            maturity_date: None,
            maturity_value_amount: None,
            ml_holder_name: None,
            next_payment: None,
            next_payment_date: None,
            next_payment_interest_amount: None,
            next_payment_principal_amount: None,
            open_date: None,
            original_interest_rate: None,
            original_maturity_date: None,
            original_school: None,
            other_nonvest_amount: None,
            other_vest_amount: None,
            out_of_school_date: None,
            owner: None,
            past_due_amount: None,
            payment_due_date: None,
            payment_min_amount: None,
            payments_made: None,
            payments_remaining: None,
            payoff_amount: None,
            payoff_amount_date: None,
            period_deposit_amount: None,
            period_end_date: None,
            period_interest_amount: None,
            period_interest_rate: None,
            period_start_date: None,
            pre_tax_amount: None,
            previous_balance: None,
            principal_balance: None,
            profit_sharing_amount: None,
            projected_interest: None,
            recurring_payment_amount: None,
            remaining_term_of_ml: None,
            repayment_plan: None,
            repayment_plan_end_date: None,
            repayment_plan_start_date: None,
            reward_earned_balance: None,
            rollover_amount: None,
            rollover_ltd: None,
            short_balance: None,
            statement_close_balance: None,
            statement_close_date: None,
            statement_credit_amount: None,
            statement_end_date: None,
            statement_finance_amount: None,
            statement_purchase_amount: None,
            statement_start_date: None,
            term_of_ml: None,
            total_amount_paid: None,
            total_interest_paid: None,
            total_principal_paid: None,
            vested_balance: None,
            weighted_interest_rate: None,
            ytd_insurance_paid: None,
            ytd_interest_paid: None,
            ytd_principal_paid: None,
            ytd_tax_paid: None,
        }
    }
}

