/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoteMxTransactionDocumentsApiMxComUsersUserGuidTransactionsBody {
    #[serde(rename = "accountGuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_guid: Option<Option<String>>,
    #[serde(rename = "accountId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<Option<String>>,
    #[serde(rename = "amount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Option<f64>>,
    #[serde(rename = "category", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category: Option<Option<String>>,
    #[serde(rename = "categoryGuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category_guid: Option<Option<String>>,
    #[serde(rename = "checkNumberString", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub check_number_string: Option<Option<String>>,
    #[serde(rename = "createdAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<Option<String>>,
    #[serde(rename = "currencyCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency_code: Option<Option<String>>,
    #[serde(rename = "date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "extendedTransactionType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub extended_transaction_type: Option<Option<String>>,
    #[serde(rename = "guid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub guid: Option<Option<String>>,
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "isBillPay", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_bill_pay: Option<Option<bool>>,
    #[serde(rename = "isDirectDeposit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_direct_deposit: Option<Option<bool>>,
    #[serde(rename = "isExpense", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_expense: Option<Option<bool>>,
    #[serde(rename = "isFee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_fee: Option<Option<bool>>,
    #[serde(rename = "isIncome", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_income: Option<Option<bool>>,
    #[serde(rename = "isInternational", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_international: Option<Option<bool>>,
    #[serde(rename = "isManual", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_manual: Option<Option<bool>>,
    #[serde(rename = "isOverdraftFee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_overdraft_fee: Option<Option<bool>>,
    #[serde(rename = "isPayrollAdvance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_payroll_advance: Option<Option<bool>>,
    #[serde(rename = "isRecurring", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_recurring: Option<Option<bool>>,
    #[serde(rename = "isSubscription", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_subscription: Option<Option<bool>>,
    #[serde(rename = "latitude", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<Option<f64>>,
    #[serde(rename = "localizedDescription", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub localized_description: Option<Option<String>>,
    #[serde(rename = "localizedMemo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub localized_memo: Option<Option<String>>,
    #[serde(rename = "longitude", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<Option<f64>>,
    #[serde(rename = "memberGuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub member_guid: Option<Option<String>>,
    #[serde(rename = "memberIsManagedByUser", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub member_is_managed_by_user: Option<Option<bool>>,
    #[serde(rename = "memo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub memo: Option<Option<String>>,
    #[serde(rename = "merchantCategoryCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub merchant_category_code: Option<Option<i32>>,
    #[serde(rename = "merchantGuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub merchant_guid: Option<Option<String>>,
    #[serde(rename = "merchantLocationGuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub merchant_location_guid: Option<Option<String>>,
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<String>>,
    #[serde(rename = "originalDescription", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub original_description: Option<Option<String>>,
    #[serde(rename = "postedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub posted_at: Option<Option<String>>,
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    #[serde(rename = "topLevelCategory", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub top_level_category: Option<Option<String>>,
    #[serde(rename = "transactedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub transacted_at: Option<Option<String>>,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    #[serde(rename = "updatedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<Option<String>>,
    #[serde(rename = "userGuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_guid: Option<Option<String>>,
    #[serde(rename = "userId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<String>>,
}

impl RemoteMxTransactionDocumentsApiMxComUsersUserGuidTransactionsBody {
    pub fn new() -> RemoteMxTransactionDocumentsApiMxComUsersUserGuidTransactionsBody {
        RemoteMxTransactionDocumentsApiMxComUsersUserGuidTransactionsBody {
            account_guid: None,
            account_id: None,
            amount: None,
            category: None,
            category_guid: None,
            check_number_string: None,
            created_at: None,
            currency_code: None,
            date: None,
            description: None,
            extended_transaction_type: None,
            guid: None,
            id: None,
            is_bill_pay: None,
            is_direct_deposit: None,
            is_expense: None,
            is_fee: None,
            is_income: None,
            is_international: None,
            is_manual: None,
            is_overdraft_fee: None,
            is_payroll_advance: None,
            is_recurring: None,
            is_subscription: None,
            latitude: None,
            localized_description: None,
            localized_memo: None,
            longitude: None,
            member_guid: None,
            member_is_managed_by_user: None,
            memo: None,
            merchant_category_code: None,
            merchant_guid: None,
            merchant_location_guid: None,
            metadata: None,
            original_description: None,
            posted_at: None,
            status: None,
            top_level_category: None,
            transacted_at: None,
            r#type: None,
            updated_at: None,
            user_guid: None,
            user_id: None,
        }
    }
}

