/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoteMxAccountDocumentsApiMxComUsersUserGuidAccountsBody {
    #[serde(rename = "accountNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_number: Option<Option<String>>,
    #[serde(rename = "accountNumberSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_number_set_by: Option<Option<i32>>,
    #[serde(rename = "accountOwnership", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_ownership: Option<Option<String>>,
    #[serde(rename = "annuityPolicyToDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub annuity_policy_to_date: Option<Option<String>>,
    #[serde(rename = "annuityProvider", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub annuity_provider: Option<Option<String>>,
    #[serde(rename = "annuityTermYear", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub annuity_term_year: Option<Option<i32>>,
    #[serde(rename = "apr", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub apr: Option<Option<f64>>,
    #[serde(rename = "aprSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub apr_set_by: Option<Option<i32>>,
    #[serde(rename = "apy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub apy: Option<Option<f64>>,
    #[serde(rename = "apySetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub apy_set_by: Option<Option<i32>>,
    #[serde(rename = "availableBalance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub available_balance: Option<Option<f64>>,
    #[serde(rename = "availableBalanceSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub available_balance_set_by: Option<Option<i32>>,
    #[serde(rename = "availableCredit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub available_credit: Option<Option<f64>>,
    #[serde(rename = "availableCreditSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub available_credit_set_by: Option<Option<i32>>,
    #[serde(rename = "balance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub balance: Option<Option<f64>>,
    #[serde(rename = "balanceSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub balance_set_by: Option<Option<i32>>,
    #[serde(rename = "calculatedApr", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub calculated_apr: Option<Option<f64>>,
    #[serde(rename = "cashBalance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cash_balance: Option<Option<f64>>,
    #[serde(rename = "cashBalanceSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cash_balance_set_by: Option<Option<i32>>,
    #[serde(rename = "cashSurrenderValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cash_surrender_value: Option<Option<f64>>,
    #[serde(rename = "cashSurrenderValueSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cash_surrender_value_set_by: Option<Option<i32>>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "creditLimit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub credit_limit: Option<Option<f64>>,
    #[serde(rename = "creditLimitSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub credit_limit_set_by: Option<Option<i32>>,
    #[serde(rename = "currencyCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency_code: Option<Option<String>>,
    #[serde(rename = "currencyCodeSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency_code_set_by: Option<Option<i32>>,
    #[serde(rename = "dayPaymentIsDue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub day_payment_is_due: Option<Option<i32>>,
    #[serde(rename = "dayPaymentIsDueSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub day_payment_is_due_set_by: Option<Option<i32>>,
    #[serde(rename = "deathBenefit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub death_benefit: Option<Option<i32>>,
    #[serde(rename = "deathBenefitSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub death_benefit_set_by: Option<Option<i32>>,
    #[serde(rename = "federalInsuranceStatus", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub federal_insurance_status: Option<Option<String>>,
    #[serde(rename = "feedAccountNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_account_number: Option<Option<String>>,
    #[serde(rename = "feedAccountSubtype", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_account_subtype: Option<Option<i32>>,
    #[serde(rename = "feedAccountType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_account_type: Option<Option<i32>>,
    #[serde(rename = "feedApr", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_apr: Option<Option<f64>>,
    #[serde(rename = "feedApy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_apy: Option<Option<f64>>,
    #[serde(rename = "feedAvailableBalance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_available_balance: Option<Option<f64>>,
    #[serde(rename = "feedBalance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_balance: Option<Option<f64>>,
    #[serde(rename = "feedCashBalance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_cash_balance: Option<Option<f64>>,
    #[serde(rename = "feedCashSurrenderValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_cash_surrender_value: Option<Option<f64>>,
    #[serde(rename = "feedCreditLimit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_credit_limit: Option<Option<f64>>,
    #[serde(rename = "feedCurrencyCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_currency_code: Option<Option<String>>,
    #[serde(rename = "feedDayPaymentIsDue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_day_payment_is_due: Option<Option<i32>>,
    #[serde(rename = "feedDeathBenefit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_death_benefit: Option<Option<i32>>,
    #[serde(rename = "feedHoldingsValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_holdings_value: Option<Option<f64>>,
    #[serde(rename = "feedInterestRate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_interest_rate: Option<Option<f64>>,
    #[serde(rename = "feedIsClosed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_is_closed: Option<Option<bool>>,
    #[serde(rename = "feedLastPayment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_last_payment: Option<Option<f64>>,
    #[serde(rename = "feedLastPaymentAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_last_payment_at: Option<Option<String>>,
    #[serde(rename = "feedLoanAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_loan_amount: Option<Option<f64>>,
    #[serde(rename = "feedMaturesOn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_matures_on: Option<Option<String>>,
    #[serde(rename = "feedMinimumBalance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_minimum_balance: Option<Option<f64>>,
    #[serde(rename = "feedMinimumPayment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_minimum_payment: Option<Option<f64>>,
    #[serde(rename = "feedName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_name: Option<Option<String>>,
    #[serde(rename = "feedNickname", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_nickname: Option<Option<String>>,
    #[serde(rename = "feedOriginalBalance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_original_balance: Option<Option<f64>>,
    #[serde(rename = "feedPaymentDueAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_payment_due_at: Option<Option<String>>,
    #[serde(rename = "feedPayoffBalance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_payoff_balance: Option<Option<f64>>,
    #[serde(rename = "feedRoutingNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_routing_number: Option<Option<String>>,
    #[serde(rename = "feedStartedOn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_started_on: Option<Option<String>>,
    #[serde(rename = "feedStatementBalance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_statement_balance: Option<Option<f64>>,
    #[serde(rename = "feedTotalAccountValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feed_total_account_value: Option<Option<f64>>,
    #[serde(rename = "guid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub guid: Option<Option<String>>,
    #[serde(rename = "holdingsValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub holdings_value: Option<Option<f64>>,
    #[serde(rename = "holdingsValueSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub holdings_value_set_by: Option<Option<i32>>,
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "importedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub imported_at: Option<Option<String>>,
    #[serde(rename = "institutionCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub institution_code: Option<Option<String>>,
    #[serde(rename = "institutionGuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub institution_guid: Option<Option<String>>,
    #[serde(rename = "insuredName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub insured_name: Option<Option<String>>,
    #[serde(rename = "interestRate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub interest_rate: Option<Option<f64>>,
    #[serde(rename = "interestRateSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub interest_rate_set_by: Option<Option<i32>>,
    #[serde(rename = "isClosed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_closed: Option<Option<bool>>,
    #[serde(rename = "isClosedSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_closed_set_by: Option<Option<i32>>,
    #[serde(rename = "isHidden", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_hidden: Option<Option<bool>>,
    #[serde(rename = "isManual", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_manual: Option<Option<bool>>,
    #[serde(rename = "lastPayment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_payment: Option<Option<f64>>,
    #[serde(rename = "lastPaymentAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_payment_at: Option<Option<String>>,
    #[serde(rename = "lastPaymentAtSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_payment_at_set_by: Option<Option<i32>>,
    #[serde(rename = "lastPaymentSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_payment_set_by: Option<Option<i32>>,
    #[serde(rename = "loanAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub loan_amount: Option<Option<f64>>,
    #[serde(rename = "loanAmountSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub loan_amount_set_by: Option<Option<i32>>,
    #[serde(rename = "marginBalance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub margin_balance: Option<Option<f64>>,
    #[serde(rename = "maturesOn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub matures_on: Option<Option<String>>,
    #[serde(rename = "maturesOnSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub matures_on_set_by: Option<Option<i32>>,
    #[serde(rename = "memberGuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub member_guid: Option<Option<String>>,
    #[serde(rename = "memberId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub member_id: Option<Option<String>>,
    #[serde(rename = "memberIsManagedByUser", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub member_is_managed_by_user: Option<Option<bool>>,
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<String>>,
    #[serde(rename = "minimumBalance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub minimum_balance: Option<Option<f64>>,
    #[serde(rename = "minimumBalanceSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub minimum_balance_set_by: Option<Option<i32>>,
    #[serde(rename = "minimumPayment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub minimum_payment: Option<Option<f64>>,
    #[serde(rename = "minimumPaymentSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub minimum_payment_set_by: Option<Option<i32>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "nameSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name_set_by: Option<Option<i32>>,
    #[serde(rename = "nickname", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nickname: Option<Option<String>>,
    #[serde(rename = "nicknameSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nickname_set_by: Option<Option<i32>>,
    #[serde(rename = "originalBalance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub original_balance: Option<Option<f64>>,
    #[serde(rename = "originalBalanceSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub original_balance_set_by: Option<Option<i32>>,
    #[serde(rename = "payOutAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pay_out_amount: Option<Option<f64>>,
    #[serde(rename = "paymentDueAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payment_due_at: Option<Option<String>>,
    #[serde(rename = "paymentDueAtSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payment_due_at_set_by: Option<Option<i32>>,
    #[serde(rename = "payoffBalance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payoff_balance: Option<Option<f64>>,
    #[serde(rename = "payoffBalanceSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payoff_balance_set_by: Option<Option<i32>>,
    #[serde(rename = "premiumAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub premium_amount: Option<Option<f64>>,
    #[serde(rename = "propertyType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub property_type: Option<Option<String>>,
    #[serde(rename = "routingNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub routing_number: Option<Option<String>>,
    #[serde(rename = "startedOn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub started_on: Option<Option<String>>,
    #[serde(rename = "startedOnSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub started_on_set_by: Option<Option<i32>>,
    #[serde(rename = "statementBalance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub statement_balance: Option<Option<f64>>,
    #[serde(rename = "statementBalanceSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub statement_balance_set_by: Option<Option<i32>>,
    #[serde(rename = "subtype", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subtype: Option<Option<String>>,
    #[serde(rename = "subtypeSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subtype_set_by: Option<Option<i32>>,
    #[serde(rename = "todayUglAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub today_ugl_amount: Option<Option<f64>>,
    #[serde(rename = "todayUglPercentage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub today_ugl_percentage: Option<Option<f64>>,
    #[serde(rename = "totalAccountValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_account_value: Option<Option<f64>>,
    #[serde(rename = "totalAccountValueSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_account_value_set_by: Option<Option<i32>>,
    #[serde(rename = "totalAccountValueUgl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_account_value_ugl: Option<Option<f64>>,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    #[serde(rename = "typeSetBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub type_set_by: Option<Option<i32>>,
    #[serde(rename = "updatedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<Option<String>>,
    #[serde(rename = "userGuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_guid: Option<Option<String>>,
    #[serde(rename = "userId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<String>>,
}

impl RemoteMxAccountDocumentsApiMxComUsersUserGuidAccountsBody {
    pub fn new() -> RemoteMxAccountDocumentsApiMxComUsersUserGuidAccountsBody {
        RemoteMxAccountDocumentsApiMxComUsersUserGuidAccountsBody {
            account_number: None,
            account_number_set_by: None,
            account_ownership: None,
            annuity_policy_to_date: None,
            annuity_provider: None,
            annuity_term_year: None,
            apr: None,
            apr_set_by: None,
            apy: None,
            apy_set_by: None,
            available_balance: None,
            available_balance_set_by: None,
            available_credit: None,
            available_credit_set_by: None,
            balance: None,
            balance_set_by: None,
            calculated_apr: None,
            cash_balance: None,
            cash_balance_set_by: None,
            cash_surrender_value: None,
            cash_surrender_value_set_by: None,
            created_at: None,
            credit_limit: None,
            credit_limit_set_by: None,
            currency_code: None,
            currency_code_set_by: None,
            day_payment_is_due: None,
            day_payment_is_due_set_by: None,
            death_benefit: None,
            death_benefit_set_by: None,
            federal_insurance_status: None,
            feed_account_number: None,
            feed_account_subtype: None,
            feed_account_type: None,
            feed_apr: None,
            feed_apy: None,
            feed_available_balance: None,
            feed_balance: None,
            feed_cash_balance: None,
            feed_cash_surrender_value: None,
            feed_credit_limit: None,
            feed_currency_code: None,
            feed_day_payment_is_due: None,
            feed_death_benefit: None,
            feed_holdings_value: None,
            feed_interest_rate: None,
            feed_is_closed: None,
            feed_last_payment: None,
            feed_last_payment_at: None,
            feed_loan_amount: None,
            feed_matures_on: None,
            feed_minimum_balance: None,
            feed_minimum_payment: None,
            feed_name: None,
            feed_nickname: None,
            feed_original_balance: None,
            feed_payment_due_at: None,
            feed_payoff_balance: None,
            feed_routing_number: None,
            feed_started_on: None,
            feed_statement_balance: None,
            feed_total_account_value: None,
            guid: None,
            holdings_value: None,
            holdings_value_set_by: None,
            id: None,
            imported_at: None,
            institution_code: None,
            institution_guid: None,
            insured_name: None,
            interest_rate: None,
            interest_rate_set_by: None,
            is_closed: None,
            is_closed_set_by: None,
            is_hidden: None,
            is_manual: None,
            last_payment: None,
            last_payment_at: None,
            last_payment_at_set_by: None,
            last_payment_set_by: None,
            loan_amount: None,
            loan_amount_set_by: None,
            margin_balance: None,
            matures_on: None,
            matures_on_set_by: None,
            member_guid: None,
            member_id: None,
            member_is_managed_by_user: None,
            metadata: None,
            minimum_balance: None,
            minimum_balance_set_by: None,
            minimum_payment: None,
            minimum_payment_set_by: None,
            name: None,
            name_set_by: None,
            nickname: None,
            nickname_set_by: None,
            original_balance: None,
            original_balance_set_by: None,
            pay_out_amount: None,
            payment_due_at: None,
            payment_due_at_set_by: None,
            payoff_balance: None,
            payoff_balance_set_by: None,
            premium_amount: None,
            property_type: None,
            routing_number: None,
            started_on: None,
            started_on_set_by: None,
            statement_balance: None,
            statement_balance_set_by: None,
            subtype: None,
            subtype_set_by: None,
            today_ugl_amount: None,
            today_ugl_percentage: None,
            total_account_value: None,
            total_account_value_set_by: None,
            total_account_value_ugl: None,
            r#type: None,
            type_set_by: None,
            updated_at: None,
            user_guid: None,
            user_id: None,
        }
    }
}

