/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoteMxConnectionDocumentsApiMxComUsersUserGuidMembersMemberGuidBody {
    #[serde(rename = "aggregatedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub aggregated_at: Option<Option<String>>,
    #[serde(rename = "backgroundAggregationIsDisabled", skip_serializing_if = "Option::is_none")]
    pub background_aggregation_is_disabled: Option<bool>,
    #[serde(rename = "connectionStatus", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub connection_status: Option<Option<String>>,
    #[serde(rename = "connectionStatusMessage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub connection_status_message: Option<Option<String>>,
    #[serde(rename = "guid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub guid: Option<Option<String>>,
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "institutionCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub institution_code: Option<Option<String>>,
    #[serde(rename = "institutionGuid", skip_serializing_if = "Option::is_none")]
    pub institution_guid: Option<String>,
    #[serde(rename = "isBeingAggregated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_being_aggregated: Option<Option<bool>>,
    #[serde(rename = "isManagedByUser", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_managed_by_user: Option<Option<bool>>,
    #[serde(rename = "isManual", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_manual: Option<Option<bool>>,
    #[serde(rename = "isOAuth", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_o_auth: Option<Option<bool>>,
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<String>>,
    #[serde(rename = "mostRecentJobDetailCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub most_recent_job_detail_code: Option<Option<i32>>,
    #[serde(rename = "mostRecentJobDetailText", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub most_recent_job_detail_text: Option<Option<bool>>,
    #[serde(rename = "mostRecentJobGuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub most_recent_job_guid: Option<Option<String>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "needsUpdatedCredentials", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub needs_updated_credentials: Option<Option<bool>>,
    #[serde(rename = "oauthWindowUri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub oauth_window_uri: Option<Option<String>>,
    #[serde(rename = "successfullyAggregatedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub successfully_aggregated_at: Option<Option<String>>,
    /// The use case associated with the member. Valid values are `PFM` and/or `MONEY_MOVEMENT`. Only set this if you've met with MX and have opted in to using this field.
    #[serde(rename = "useCases", skip_serializing_if = "Option::is_none")]
    pub use_cases: Option<Vec<UseCases>>,
    #[serde(rename = "userGuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_guid: Option<Option<String>>,
    #[serde(rename = "userId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<String>>,
}

impl RemoteMxConnectionDocumentsApiMxComUsersUserGuidMembersMemberGuidBody {
    pub fn new() -> RemoteMxConnectionDocumentsApiMxComUsersUserGuidMembersMemberGuidBody {
        RemoteMxConnectionDocumentsApiMxComUsersUserGuidMembersMemberGuidBody {
            aggregated_at: None,
            background_aggregation_is_disabled: None,
            connection_status: None,
            connection_status_message: None,
            guid: None,
            id: None,
            institution_code: None,
            institution_guid: None,
            is_being_aggregated: None,
            is_managed_by_user: None,
            is_manual: None,
            is_o_auth: None,
            metadata: None,
            most_recent_job_detail_code: None,
            most_recent_job_detail_text: None,
            most_recent_job_guid: None,
            name: None,
            needs_updated_credentials: None,
            oauth_window_uri: None,
            successfully_aggregated_at: None,
            use_cases: None,
            user_guid: None,
            user_id: None,
        }
    }
}
/// The use case associated with the member. Valid values are `PFM` and/or `MONEY_MOVEMENT`. Only set this if you've met with MX and have opted in to using this field.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UseCases {
    #[serde(rename = "MONEY_MOVEMENT")]
    MoneyMovement,
    #[serde(rename = "PFM")]
    Pfm,
}

impl Default for UseCases {
    fn default() -> UseCases {
        Self::MoneyMovement
    }
}

