/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RemoteFinicityConnection : Remote Data about the Connection.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoteFinicityConnection {
    /// The ID of the Connection.
    #[serde(rename = "connectionId")]
    pub connection_id: String,
    /// The ID of the Profile.
    #[serde(rename = "profileId")]
    pub profile_id: String,
    /// The type of Remote data
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "documents")]
    pub documents: Box<models::RemoteFinicityConnectionDocuments>,
}

impl RemoteFinicityConnection {
    /// Remote Data about the Connection.
    pub fn new(connection_id: String, profile_id: String, r#type: Type, documents: models::RemoteFinicityConnectionDocuments) -> RemoteFinicityConnection {
        RemoteFinicityConnection {
            connection_id,
            profile_id,
            r#type,
            documents: Box::new(documents),
        }
    }
}
/// The type of Remote data
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "FINICITY")]
    Finicity,
}

impl Default for Type {
    fn default() -> Type {
        Self::Finicity
    }
}

