/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RemotePlaidConnectionDocumentsEnvironmentPlaidComItemGetBody : Metadata about the Item.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemotePlaidConnectionDocumentsEnvironmentPlaidComItemGetBody {
    /// The method used to populate Auth data for the Item. This field is only populated for Items that have had Auth numbers data set on at least one of its accounts, and will be `null` otherwise. For info about the various flows, see our [Auth coverage documentation](https://plaid.com/docs/auth/coverage/).  `INSTANT_AUTH`: The Item's Auth data was provided directly by the user's institution connection.  `INSTANT_MATCH`: The Item's Auth data was provided via the Instant Match fallback flow.  `AUTOMATED_MICRODEPOSITS`: The Item's Auth data was provided via the Automated Micro-deposits flow.  `SAME_DAY_MICRODEPOSITS`: The Item's Auth data was provided via the Same Day Micro-deposits flow.  `INSTANT_MICRODEPOSITS`: The Item's Auth data was provided via the Instant Micro-deposits flow.  `DATABASE_MATCH`: The Item's Auth data was provided via the Database Match flow.  `DATABASE_INSIGHTS`: The Item's Auth data was provided via the Database Insights flow.  `TRANSFER_MIGRATED`: The Item's Auth data was provided via [`/transfer/migrate_account`](https://plaid.com/docs/api/products/transfer/account-linking/#migrate-account-into-transfers).  `INVESTMENTS_FALLBACK`: The Item's Auth data for Investments Move was provided via a [fallback flow](https://plaid.com/docs/investments-move/#fallback-flows).
    #[serde(rename = "authMethod", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub auth_method: Option<Option<AuthMethod>>,
    /// A list of products available for the Item that have not yet been accessed. The contents of this array will be mutually exclusive with `billed_products`.
    #[serde(rename = "availableProducts")]
    pub available_products: Vec<AvailableProducts>,
    /// A list of products that have been billed for the Item. The contents of this array will be mutually exclusive with `available_products`. Note - `billed_products` is populated in all environments but only requests in Production are billed. Also note that products that are billed on a pay-per-call basis rather than a pay-per-Item basis, such as `balance`, will not appear here. 
    #[serde(rename = "billedProducts")]
    pub billed_products: Vec<BilledProducts>,
    /// The date and time at which the Item's access consent will expire, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format. If the Item does not have consent expiration scheduled, this field will be `null`. Currently, only institutions in Europe and a small number of institutions in the US have expiring consent. For a list of US institutions that currently expire consent, see the [OAuth Guide](https://plaid.com/docs/link/oauth/#refreshing-item-consent).
    #[serde(rename = "consentExpirationTime", deserialize_with = "Option::deserialize")]
    pub consent_expiration_time: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// A list of products that the user has consented to for the Item via [Data Transparency Messaging](https://plaid.com/docs/link/data-transparency-messaging-migration-guide). This will consist of all products where both of the following are true: the user has consented to the required data scopes for that product and you have Production access for that product. 
    #[serde(rename = "consentedProducts", skip_serializing_if = "Option::is_none")]
    pub consented_products: Option<Vec<ConsentedProducts>>,
    #[serde(rename = "error", deserialize_with = "Option::deserialize")]
    pub error: Option<models::Error>,
    /// The Plaid Institution ID associated with the Item. Field is `null` for Items created without an institution connection, such as Items created via Same Day Micro-deposits.
    #[serde(rename = "institutionId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub institution_id: Option<Option<String>>,
    /// The name of the institution associated with the Item. Field is `null` for Items created without an institution connection, such as Items created via Same Day Micro-deposits.
    #[serde(rename = "institutionName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub institution_name: Option<Option<String>>,
    /// The Plaid Item ID. The `item_id` is always unique; linking the same account at the same institution twice will result in two Items with different `item_id` values. Like all Plaid identifiers, the `item_id` is case-sensitive.
    #[serde(rename = "itemId")]
    pub item_id: String,
    /// A list of products added to the Item. In almost all cases, this will be the same as the `billed_products` field. For some products, it is possible for the product to be added to an Item but not yet billed (e.g. Assets, before `/asset_report/create` has been called, or Auth or Identity when added as Optional Products but before their endpoints have been called), in which case the product may appear in `products` but not in `billed_products`. 
    #[serde(rename = "products", skip_serializing_if = "Option::is_none")]
    pub products: Option<Vec<Products>>,
    /// Indicates whether an Item requires user interaction to be updated, which can be the case for Items with some forms of two-factor authentication.  `background` - Item can be updated in the background  `user_present_required` - Item requires user interaction to be updated
    #[serde(rename = "updateType")]
    pub update_type: UpdateType,
    /// The URL registered to receive webhooks for the Item.
    #[serde(rename = "webhook", deserialize_with = "Option::deserialize")]
    pub webhook: Option<String>,
}

impl RemotePlaidConnectionDocumentsEnvironmentPlaidComItemGetBody {
    /// Metadata about the Item.
    pub fn new(available_products: Vec<AvailableProducts>, billed_products: Vec<BilledProducts>, consent_expiration_time: Option<chrono::DateTime<chrono::FixedOffset>>, error: Option<models::Error>, item_id: String, update_type: UpdateType, webhook: Option<String>) -> RemotePlaidConnectionDocumentsEnvironmentPlaidComItemGetBody {
        RemotePlaidConnectionDocumentsEnvironmentPlaidComItemGetBody {
            auth_method: None,
            available_products,
            billed_products,
            consent_expiration_time,
            consented_products: None,
            error,
            institution_id: None,
            institution_name: None,
            item_id,
            products: None,
            update_type,
            webhook,
        }
    }
}
/// The method used to populate Auth data for the Item. This field is only populated for Items that have had Auth numbers data set on at least one of its accounts, and will be `null` otherwise. For info about the various flows, see our [Auth coverage documentation](https://plaid.com/docs/auth/coverage/).  `INSTANT_AUTH`: The Item's Auth data was provided directly by the user's institution connection.  `INSTANT_MATCH`: The Item's Auth data was provided via the Instant Match fallback flow.  `AUTOMATED_MICRODEPOSITS`: The Item's Auth data was provided via the Automated Micro-deposits flow.  `SAME_DAY_MICRODEPOSITS`: The Item's Auth data was provided via the Same Day Micro-deposits flow.  `INSTANT_MICRODEPOSITS`: The Item's Auth data was provided via the Instant Micro-deposits flow.  `DATABASE_MATCH`: The Item's Auth data was provided via the Database Match flow.  `DATABASE_INSIGHTS`: The Item's Auth data was provided via the Database Insights flow.  `TRANSFER_MIGRATED`: The Item's Auth data was provided via [`/transfer/migrate_account`](https://plaid.com/docs/api/products/transfer/account-linking/#migrate-account-into-transfers).  `INVESTMENTS_FALLBACK`: The Item's Auth data for Investments Move was provided via a [fallback flow](https://plaid.com/docs/investments-move/#fallback-flows).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthMethod {
    #[serde(rename = "INSTANT_AUTH")]
    InstantAuth,
    #[serde(rename = "INSTANT_MATCH")]
    InstantMatch,
    #[serde(rename = "AUTOMATED_MICRODEPOSITS")]
    AutomatedMicrodeposits,
    #[serde(rename = "SAME_DAY_MICRODEPOSITS")]
    SameDayMicrodeposits,
    #[serde(rename = "INSTANT_MICRODEPOSITS")]
    InstantMicrodeposits,
    #[serde(rename = "DATABASE_MATCH")]
    DatabaseMatch,
    #[serde(rename = "DATABASE_INSIGHTS")]
    DatabaseInsights,
    #[serde(rename = "TRANSFER_MIGRATED")]
    TransferMigrated,
    #[serde(rename = "INVESTMENTS_FALLBACK")]
    InvestmentsFallback,
}

impl Default for AuthMethod {
    fn default() -> AuthMethod {
        Self::InstantAuth
    }
}
/// A list of products available for the Item that have not yet been accessed. The contents of this array will be mutually exclusive with `billed_products`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AvailableProducts {
    #[serde(rename = "assets")]
    Assets,
    #[serde(rename = "auth")]
    Auth,
    #[serde(rename = "balance")]
    Balance,
    #[serde(rename = "balance_plus")]
    BalancePlus,
    #[serde(rename = "beacon")]
    Beacon,
    #[serde(rename = "identity")]
    Identity,
    #[serde(rename = "identity_match")]
    IdentityMatch,
    #[serde(rename = "investments")]
    Investments,
    #[serde(rename = "investments_auth")]
    InvestmentsAuth,
    #[serde(rename = "liabilities")]
    Liabilities,
    #[serde(rename = "payment_initiation")]
    PaymentInitiation,
    #[serde(rename = "identity_verification")]
    IdentityVerification,
    #[serde(rename = "transactions")]
    Transactions,
    #[serde(rename = "credit_details")]
    CreditDetails,
    #[serde(rename = "income")]
    Income,
    #[serde(rename = "income_verification")]
    IncomeVerification,
    #[serde(rename = "standing_orders")]
    StandingOrders,
    #[serde(rename = "transfer")]
    Transfer,
    #[serde(rename = "employment")]
    Employment,
    #[serde(rename = "recurring_transactions")]
    RecurringTransactions,
    #[serde(rename = "transactions_refresh")]
    TransactionsRefresh,
    #[serde(rename = "signal")]
    Signal,
    #[serde(rename = "statements")]
    Statements,
    #[serde(rename = "processor_payments")]
    ProcessorPayments,
    #[serde(rename = "processor_identity")]
    ProcessorIdentity,
    #[serde(rename = "profile")]
    Profile,
    #[serde(rename = "cra_base_report")]
    CraBaseReport,
    #[serde(rename = "cra_income_insights")]
    CraIncomeInsights,
    #[serde(rename = "cra_partner_insights")]
    CraPartnerInsights,
    #[serde(rename = "cra_network_insights")]
    CraNetworkInsights,
    #[serde(rename = "cra_cashflow_insights")]
    CraCashflowInsights,
    #[serde(rename = "cra_monitoring")]
    CraMonitoring,
    #[serde(rename = "cra_lend_score")]
    CraLendScore,
    #[serde(rename = "cra_plaid_credit_score")]
    CraPlaidCreditScore,
    #[serde(rename = "layer")]
    Layer,
    #[serde(rename = "pay_by_bank")]
    PayByBank,
    #[serde(rename = "protect_linked_bank")]
    ProtectLinkedBank,
}

impl Default for AvailableProducts {
    fn default() -> AvailableProducts {
        Self::Assets
    }
}
/// A list of products that have been billed for the Item. The contents of this array will be mutually exclusive with `available_products`. Note - `billed_products` is populated in all environments but only requests in Production are billed. Also note that products that are billed on a pay-per-call basis rather than a pay-per-Item basis, such as `balance`, will not appear here. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BilledProducts {
    #[serde(rename = "assets")]
    Assets,
    #[serde(rename = "auth")]
    Auth,
    #[serde(rename = "balance")]
    Balance,
    #[serde(rename = "balance_plus")]
    BalancePlus,
    #[serde(rename = "beacon")]
    Beacon,
    #[serde(rename = "identity")]
    Identity,
    #[serde(rename = "identity_match")]
    IdentityMatch,
    #[serde(rename = "investments")]
    Investments,
    #[serde(rename = "investments_auth")]
    InvestmentsAuth,
    #[serde(rename = "liabilities")]
    Liabilities,
    #[serde(rename = "payment_initiation")]
    PaymentInitiation,
    #[serde(rename = "identity_verification")]
    IdentityVerification,
    #[serde(rename = "transactions")]
    Transactions,
    #[serde(rename = "credit_details")]
    CreditDetails,
    #[serde(rename = "income")]
    Income,
    #[serde(rename = "income_verification")]
    IncomeVerification,
    #[serde(rename = "standing_orders")]
    StandingOrders,
    #[serde(rename = "transfer")]
    Transfer,
    #[serde(rename = "employment")]
    Employment,
    #[serde(rename = "recurring_transactions")]
    RecurringTransactions,
    #[serde(rename = "transactions_refresh")]
    TransactionsRefresh,
    #[serde(rename = "signal")]
    Signal,
    #[serde(rename = "statements")]
    Statements,
    #[serde(rename = "processor_payments")]
    ProcessorPayments,
    #[serde(rename = "processor_identity")]
    ProcessorIdentity,
    #[serde(rename = "profile")]
    Profile,
    #[serde(rename = "cra_base_report")]
    CraBaseReport,
    #[serde(rename = "cra_income_insights")]
    CraIncomeInsights,
    #[serde(rename = "cra_partner_insights")]
    CraPartnerInsights,
    #[serde(rename = "cra_network_insights")]
    CraNetworkInsights,
    #[serde(rename = "cra_cashflow_insights")]
    CraCashflowInsights,
    #[serde(rename = "cra_monitoring")]
    CraMonitoring,
    #[serde(rename = "cra_lend_score")]
    CraLendScore,
    #[serde(rename = "cra_plaid_credit_score")]
    CraPlaidCreditScore,
    #[serde(rename = "layer")]
    Layer,
    #[serde(rename = "pay_by_bank")]
    PayByBank,
    #[serde(rename = "protect_linked_bank")]
    ProtectLinkedBank,
}

impl Default for BilledProducts {
    fn default() -> BilledProducts {
        Self::Assets
    }
}
/// A list of products that the user has consented to for the Item via [Data Transparency Messaging](https://plaid.com/docs/link/data-transparency-messaging-migration-guide). This will consist of all products where both of the following are true: the user has consented to the required data scopes for that product and you have Production access for that product. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConsentedProducts {
    #[serde(rename = "assets")]
    Assets,
    #[serde(rename = "auth")]
    Auth,
    #[serde(rename = "balance")]
    Balance,
    #[serde(rename = "balance_plus")]
    BalancePlus,
    #[serde(rename = "beacon")]
    Beacon,
    #[serde(rename = "identity")]
    Identity,
    #[serde(rename = "identity_match")]
    IdentityMatch,
    #[serde(rename = "investments")]
    Investments,
    #[serde(rename = "investments_auth")]
    InvestmentsAuth,
    #[serde(rename = "liabilities")]
    Liabilities,
    #[serde(rename = "payment_initiation")]
    PaymentInitiation,
    #[serde(rename = "identity_verification")]
    IdentityVerification,
    #[serde(rename = "transactions")]
    Transactions,
    #[serde(rename = "credit_details")]
    CreditDetails,
    #[serde(rename = "income")]
    Income,
    #[serde(rename = "income_verification")]
    IncomeVerification,
    #[serde(rename = "standing_orders")]
    StandingOrders,
    #[serde(rename = "transfer")]
    Transfer,
    #[serde(rename = "employment")]
    Employment,
    #[serde(rename = "recurring_transactions")]
    RecurringTransactions,
    #[serde(rename = "transactions_refresh")]
    TransactionsRefresh,
    #[serde(rename = "signal")]
    Signal,
    #[serde(rename = "statements")]
    Statements,
    #[serde(rename = "processor_payments")]
    ProcessorPayments,
    #[serde(rename = "processor_identity")]
    ProcessorIdentity,
    #[serde(rename = "profile")]
    Profile,
    #[serde(rename = "cra_base_report")]
    CraBaseReport,
    #[serde(rename = "cra_income_insights")]
    CraIncomeInsights,
    #[serde(rename = "cra_partner_insights")]
    CraPartnerInsights,
    #[serde(rename = "cra_network_insights")]
    CraNetworkInsights,
    #[serde(rename = "cra_cashflow_insights")]
    CraCashflowInsights,
    #[serde(rename = "cra_monitoring")]
    CraMonitoring,
    #[serde(rename = "cra_lend_score")]
    CraLendScore,
    #[serde(rename = "cra_plaid_credit_score")]
    CraPlaidCreditScore,
    #[serde(rename = "layer")]
    Layer,
    #[serde(rename = "pay_by_bank")]
    PayByBank,
    #[serde(rename = "protect_linked_bank")]
    ProtectLinkedBank,
}

impl Default for ConsentedProducts {
    fn default() -> ConsentedProducts {
        Self::Assets
    }
}
/// A list of products added to the Item. In almost all cases, this will be the same as the `billed_products` field. For some products, it is possible for the product to be added to an Item but not yet billed (e.g. Assets, before `/asset_report/create` has been called, or Auth or Identity when added as Optional Products but before their endpoints have been called), in which case the product may appear in `products` but not in `billed_products`. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Products {
    #[serde(rename = "assets")]
    Assets,
    #[serde(rename = "auth")]
    Auth,
    #[serde(rename = "balance")]
    Balance,
    #[serde(rename = "balance_plus")]
    BalancePlus,
    #[serde(rename = "beacon")]
    Beacon,
    #[serde(rename = "identity")]
    Identity,
    #[serde(rename = "identity_match")]
    IdentityMatch,
    #[serde(rename = "investments")]
    Investments,
    #[serde(rename = "investments_auth")]
    InvestmentsAuth,
    #[serde(rename = "liabilities")]
    Liabilities,
    #[serde(rename = "payment_initiation")]
    PaymentInitiation,
    #[serde(rename = "identity_verification")]
    IdentityVerification,
    #[serde(rename = "transactions")]
    Transactions,
    #[serde(rename = "credit_details")]
    CreditDetails,
    #[serde(rename = "income")]
    Income,
    #[serde(rename = "income_verification")]
    IncomeVerification,
    #[serde(rename = "standing_orders")]
    StandingOrders,
    #[serde(rename = "transfer")]
    Transfer,
    #[serde(rename = "employment")]
    Employment,
    #[serde(rename = "recurring_transactions")]
    RecurringTransactions,
    #[serde(rename = "transactions_refresh")]
    TransactionsRefresh,
    #[serde(rename = "signal")]
    Signal,
    #[serde(rename = "statements")]
    Statements,
    #[serde(rename = "processor_payments")]
    ProcessorPayments,
    #[serde(rename = "processor_identity")]
    ProcessorIdentity,
    #[serde(rename = "profile")]
    Profile,
    #[serde(rename = "cra_base_report")]
    CraBaseReport,
    #[serde(rename = "cra_income_insights")]
    CraIncomeInsights,
    #[serde(rename = "cra_partner_insights")]
    CraPartnerInsights,
    #[serde(rename = "cra_network_insights")]
    CraNetworkInsights,
    #[serde(rename = "cra_cashflow_insights")]
    CraCashflowInsights,
    #[serde(rename = "cra_monitoring")]
    CraMonitoring,
    #[serde(rename = "cra_lend_score")]
    CraLendScore,
    #[serde(rename = "cra_plaid_credit_score")]
    CraPlaidCreditScore,
    #[serde(rename = "layer")]
    Layer,
    #[serde(rename = "pay_by_bank")]
    PayByBank,
    #[serde(rename = "protect_linked_bank")]
    ProtectLinkedBank,
}

impl Default for Products {
    fn default() -> Products {
        Self::Assets
    }
}
/// Indicates whether an Item requires user interaction to be updated, which can be the case for Items with some forms of two-factor authentication.  `background` - Item can be updated in the background  `user_present_required` - Item requires user interaction to be updated
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UpdateType {
    #[serde(rename = "background")]
    Background,
    #[serde(rename = "user_present_required")]
    UserPresentRequired,
}

impl Default for UpdateType {
    fn default() -> UpdateType {
        Self::Background
    }
}

