/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StudentLoanStatus : An object representing the status of the student loan
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StudentLoanStatus {
    /// The date until which the loan will be in its current status. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD). 
    #[serde(rename = "endDate", deserialize_with = "Option::deserialize")]
    pub end_date: Option<chrono::NaiveDate>,
    /// The status type of the student loan
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<Type>,
}

impl StudentLoanStatus {
    /// An object representing the status of the student loan
    pub fn new(end_date: Option<chrono::NaiveDate>, r#type: Option<Type>) -> StudentLoanStatus {
        StudentLoanStatus {
            end_date,
            r#type,
        }
    }
}
/// The status type of the student loan
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "charged off")]
    ChargedOff,
    #[serde(rename = "claim")]
    Claim,
    #[serde(rename = "consolidated")]
    Consolidated,
    #[serde(rename = "deferment")]
    Deferment,
    #[serde(rename = "delinquent")]
    Delinquent,
    #[serde(rename = "discharged")]
    Discharged,
    #[serde(rename = "extension")]
    Extension,
    #[serde(rename = "forbearance")]
    Forbearance,
    #[serde(rename = "in grace")]
    InGrace,
    #[serde(rename = "in military")]
    InMilitary,
    #[serde(rename = "in school")]
    InSchool,
    #[serde(rename = "not fully disbursed")]
    NotFullyDisbursed,
    #[serde(rename = "other")]
    Other,
    #[serde(rename = "paid in full")]
    PaidInFull,
    #[serde(rename = "refunded")]
    Refunded,
    #[serde(rename = "repayment")]
    Repayment,
    #[serde(rename = "transferred")]
    Transferred,
    #[serde(rename = "pending idr")]
    PendingIdr,
}

impl Default for Type {
    fn default() -> Type {
        Self::Cancelled
    }
}

