/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StudentRepaymentPlan : An object representing the repayment plan for the student loan
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StudentRepaymentPlan {
    /// The description of the repayment plan as provided by the servicer.
    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<String>,
    /// The type of the repayment plan.
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<Type>,
}

impl StudentRepaymentPlan {
    /// An object representing the repayment plan for the student loan
    pub fn new(description: Option<String>, r#type: Option<Type>) -> StudentRepaymentPlan {
        StudentRepaymentPlan {
            description,
            r#type,
        }
    }
}
/// The type of the repayment plan.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "extended graduated")]
    ExtendedGraduated,
    #[serde(rename = "extended standard")]
    ExtendedStandard,
    #[serde(rename = "graduated")]
    Graduated,
    #[serde(rename = "income-contingent repayment")]
    IncomeContingentRepayment,
    #[serde(rename = "income-based repayment")]
    IncomeBasedRepayment,
    #[serde(rename = "income-sensitive repayment")]
    IncomeSensitiveRepayment,
    #[serde(rename = "interest-only")]
    InterestOnly,
    #[serde(rename = "other")]
    Other,
    #[serde(rename = "pay as you earn")]
    PayAsYouEarn,
    #[serde(rename = "revised pay as you earn")]
    RevisedPayAsYouEarn,
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "saving on a valuable education")]
    SavingOnAValuableEducation,
}

impl Default for Type {
    fn default() -> Type {
        Self::ExtendedGraduated
    }
}

