/*
 * REST API
 *
 * # Overview The REST API allows you to handle authentication, manage Profiles and perform certain server-to-server operations in your Quiltt Environment.  To download and interact with detailed Profile data, including Connections, Accounts, Transactions, and Statements, use the [GraphQL API](https://www.quiltt.dev/api-reference/graphql).  See the [API Overview](https://www.quiltt.dev/api) to learn more about Quiltt's Hybrid API model.  # API Host  Auth-related requests - like issuing session tokens or introspecting credentials - use the Auth server:  <pre><code>https://auth.quiltt.io</code></pre>  All other API requests use the core API server:  <pre><code>https://api.quiltt.io</code></pre>  # Authentication  All requests, except for certain Auth endpoints, require a valid API Key secret to be passed in as a bearer token in the Authorization header:  <pre><code>Authorization: Bearer {API_KEY_SECRET}</code></pre>  You can access your API Keys in the [Quiltt Dashboard](https://dashboard.quiltt.dev/api-keys).  # Errors Unsuccessful requests will return a JSON object to help troubleshoot what went wrong.  ### StandardError A generic error with troubleshooting instructions.  Returned with all `4xx` or `5xx` HTTP status codes, except `422` errors on some REST endpoints. <SchemaDefinition schemaRef=\"#/components/schemas/RestError\" />  ### ValidationErrors One or more correctable errors encountered when attempting to create or update a record.  Returned with a `422` HTTP status code. <SchemaDefinition schemaRef=\"#/components/schemas/ValidationErrors\" /> 
 *
 * The version of the OpenAPI document: 2026-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookPayload : A Webhook Payload represents the object that the Quiltt system will deliver to your Subscription's `targetUrl`, and will include one of more Events.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookPayload {
    #[serde(rename = "environment")]
    pub environment: Box<models::Environment>,
    /// The types of events included in the Payload.
    #[serde(rename = "eventTypes")]
    pub event_types: Vec<EventTypes>,
    /// The events included in this Payload.
    #[serde(rename = "events")]
    pub events: Vec<models::WebhookPayloadEventsInner>,
}

impl WebhookPayload {
    /// A Webhook Payload represents the object that the Quiltt system will deliver to your Subscription's `targetUrl`, and will include one of more Events.
    pub fn new(environment: models::Environment, event_types: Vec<EventTypes>, events: Vec<models::WebhookPayloadEventsInner>) -> WebhookPayload {
        WebhookPayload {
            environment: Box::new(environment),
            event_types,
            events,
        }
    }
}
/// The types of events included in the Payload.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventTypes {
    #[serde(rename = "connection.created")]
    ConnectionCreated,
    #[serde(rename = "connection.synced.successful")]
    ConnectionSyncedSuccessful,
    #[serde(rename = "connection.synced.successful.initial")]
    ConnectionSyncedSuccessfulInitial,
    #[serde(rename = "connection.synced.successful.historical")]
    ConnectionSyncedSuccessfulHistorical,
    #[serde(rename = "connection.synced.errored.repairable")]
    ConnectionSyncedErroredRepairable,
    #[serde(rename = "connection.synced.errored.institution")]
    ConnectionSyncedErroredInstitution,
    #[serde(rename = "connection.synced.errored.provider")]
    ConnectionSyncedErroredProvider,
    #[serde(rename = "connection.synced.errored.service")]
    ConnectionSyncedErroredService,
    #[serde(rename = "connection.disconnected")]
    ConnectionDisconnected,
    #[serde(rename = "account.created")]
    AccountCreated,
    #[serde(rename = "account.owners_verified")]
    AccountOwnersVerified,
    #[serde(rename = "account.reconnected")]
    AccountReconnected,
    #[serde(rename = "account.verified")]
    AccountVerified,
    #[serde(rename = "balance.created")]
    BalanceCreated,
    #[serde(rename = "statement.ready")]
    StatementReady,
    #[serde(rename = "profile.created")]
    ProfileCreated,
    #[serde(rename = "profile.ready")]
    ProfileReady,
    #[serde(rename = "profile.deleted")]
    ProfileDeleted,
}

impl Default for EventTypes {
    fn default() -> EventTypes {
        Self::ConnectionCreated
    }
}

